// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bizchain/jamaah/jamaah.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DocumentHash represents a hashed document for verification (passport, visa, vaccine, health)
type DocumentHash struct {
	DocType    string `protobuf:"bytes,1,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Hash       string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	StorageRef string `protobuf:"bytes,3,opt,name=storage_ref,json=storageRef,proto3" json:"storage_ref,omitempty"`
	UploadedAt string `protobuf:"bytes,4,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
}

func (m *DocumentHash) Reset()         { *m = DocumentHash{} }
func (m *DocumentHash) String() string { return proto.CompactTextString(m) }
func (*DocumentHash) ProtoMessage()    {}
func (*DocumentHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_00675bbb5d67fc9c, []int{0}
}
func (m *DocumentHash) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DocumentHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DocumentHash.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DocumentHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentHash.Merge(m, src)
}
func (m *DocumentHash) XXX_Size() int {
	return m.Size()
}
func (m *DocumentHash) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentHash.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentHash proto.InternalMessageInfo

func (m *DocumentHash) GetDocType() string {
	if m != nil {
		return m.DocType
	}
	return ""
}

func (m *DocumentHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *DocumentHash) GetStorageRef() string {
	if m != nil {
		return m.StorageRef
	}
	return ""
}

func (m *DocumentHash) GetUploadedAt() string {
	if m != nil {
		return m.UploadedAt
	}
	return ""
}

// VaccinationRecord represents a vaccine record
type VaccinationRecord struct {
	VaccineName string `protobuf:"bytes,1,opt,name=vaccine_name,json=vaccineName,proto3" json:"vaccine_name,omitempty"`
	Date        string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Issuer      string `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Batch       string `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
}

func (m *VaccinationRecord) Reset()         { *m = VaccinationRecord{} }
func (m *VaccinationRecord) String() string { return proto.CompactTextString(m) }
func (*VaccinationRecord) ProtoMessage()    {}
func (*VaccinationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_00675bbb5d67fc9c, []int{1}
}
func (m *VaccinationRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaccinationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VaccinationRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VaccinationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaccinationRecord.Merge(m, src)
}
func (m *VaccinationRecord) XXX_Size() int {
	return m.Size()
}
func (m *VaccinationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_VaccinationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_VaccinationRecord proto.InternalMessageInfo

func (m *VaccinationRecord) GetVaccineName() string {
	if m != nil {
		return m.VaccineName
	}
	return ""
}

func (m *VaccinationRecord) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *VaccinationRecord) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *VaccinationRecord) GetBatch() string {
	if m != nil {
		return m.Batch
	}
	return ""
}

// DepartureHistoryItem represents a past departure record
type DepartureHistoryItem struct {
	PaketId uint64 `protobuf:"varint,1,opt,name=paket_id,json=paketId,proto3" json:"paket_id,omitempty"`
	Year    string `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	Status  string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Date    string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *DepartureHistoryItem) Reset()         { *m = DepartureHistoryItem{} }
func (m *DepartureHistoryItem) String() string { return proto.CompactTextString(m) }
func (*DepartureHistoryItem) ProtoMessage()    {}
func (*DepartureHistoryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_00675bbb5d67fc9c, []int{2}
}
func (m *DepartureHistoryItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DepartureHistoryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DepartureHistoryItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DepartureHistoryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartureHistoryItem.Merge(m, src)
}
func (m *DepartureHistoryItem) XXX_Size() int {
	return m.Size()
}
func (m *DepartureHistoryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartureHistoryItem.DiscardUnknown(m)
}

var xxx_messageInfo_DepartureHistoryItem proto.InternalMessageInfo

func (m *DepartureHistoryItem) GetPaketId() uint64 {
	if m != nil {
		return m.PaketId
	}
	return 0
}

func (m *DepartureHistoryItem) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *DepartureHistoryItem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DepartureHistoryItem) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

// Jamaah represents a Hajj/Umroh pilgrim (self-sovereign DID on-chain)
type Jamaah struct {
	Id               uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone            string                  `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email            string                  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address          string                  `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PassportNumber   string                  `protobuf:"bytes,6,opt,name=passport_number,json=passportNumber,proto3" json:"passport_number,omitempty"`
	PhotoHash        string                  `protobuf:"bytes,7,opt,name=photo_hash,json=photoHash,proto3" json:"photo_hash,omitempty"`
	Status           string                  `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Did              string                  `protobuf:"bytes,9,opt,name=did,proto3" json:"did,omitempty"`
	Creator          string                  `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
	Documents        []*DocumentHash         `protobuf:"bytes,11,rep,name=documents,proto3" json:"documents,omitempty"`
	Vaccinations     []*VaccinationRecord    `protobuf:"bytes,12,rep,name=vaccinations,proto3" json:"vaccinations,omitempty"`
	DepartureHistory []*DepartureHistoryItem `protobuf:"bytes,13,rep,name=departure_history,json=departureHistory,proto3" json:"departure_history,omitempty"`
	CreatedAt        string                  `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                  `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Jamaah) Reset()         { *m = Jamaah{} }
func (m *Jamaah) String() string { return proto.CompactTextString(m) }
func (*Jamaah) ProtoMessage()    {}
func (*Jamaah) Descriptor() ([]byte, []int) {
	return fileDescriptor_00675bbb5d67fc9c, []int{3}
}
func (m *Jamaah) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Jamaah) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Jamaah.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Jamaah) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jamaah.Merge(m, src)
}
func (m *Jamaah) XXX_Size() int {
	return m.Size()
}
func (m *Jamaah) XXX_DiscardUnknown() {
	xxx_messageInfo_Jamaah.DiscardUnknown(m)
}

var xxx_messageInfo_Jamaah proto.InternalMessageInfo

func (m *Jamaah) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Jamaah) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Jamaah) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Jamaah) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Jamaah) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Jamaah) GetPassportNumber() string {
	if m != nil {
		return m.PassportNumber
	}
	return ""
}

func (m *Jamaah) GetPhotoHash() string {
	if m != nil {
		return m.PhotoHash
	}
	return ""
}

func (m *Jamaah) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Jamaah) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *Jamaah) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Jamaah) GetDocuments() []*DocumentHash {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *Jamaah) GetVaccinations() []*VaccinationRecord {
	if m != nil {
		return m.Vaccinations
	}
	return nil
}

func (m *Jamaah) GetDepartureHistory() []*DepartureHistoryItem {
	if m != nil {
		return m.DepartureHistory
	}
	return nil
}

func (m *Jamaah) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Jamaah) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Params defines the parameters for the jamaah module
type Params struct {
	ZeroFeeEnabled bool `protobuf:"varint,1,opt,name=zero_fee_enabled,json=zeroFeeEnabled,proto3" json:"zero_fee_enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_00675bbb5d67fc9c, []int{4}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetZeroFeeEnabled() bool {
	if m != nil {
		return m.ZeroFeeEnabled
	}
	return false
}

// GenesisState defines the genesis state of the jamaah module
type GenesisState struct {
	JamaahList  []*Jamaah `protobuf:"bytes,1,rep,name=jamaah_list,json=jamaahList,proto3" json:"jamaah_list,omitempty"`
	JamaahCount uint64    `protobuf:"varint,2,opt,name=jamaah_count,json=jamaahCount,proto3" json:"jamaah_count,omitempty"`
	Params      *Params   `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_00675bbb5d67fc9c, []int{5}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetJamaahList() []*Jamaah {
	if m != nil {
		return m.JamaahList
	}
	return nil
}

func (m *GenesisState) GetJamaahCount() uint64 {
	if m != nil {
		return m.JamaahCount
	}
	return 0
}

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*DocumentHash)(nil), "bizchain.jamaah.DocumentHash")
	proto.RegisterType((*VaccinationRecord)(nil), "bizchain.jamaah.VaccinationRecord")
	proto.RegisterType((*DepartureHistoryItem)(nil), "bizchain.jamaah.DepartureHistoryItem")
	proto.RegisterType((*Jamaah)(nil), "bizchain.jamaah.Jamaah")
	proto.RegisterType((*Params)(nil), "bizchain.jamaah.Params")
	proto.RegisterType((*GenesisState)(nil), "bizchain.jamaah.GenesisState")
}

func init() { proto.RegisterFile("bizchain/jamaah/jamaah.proto", fileDescriptor_00675bbb5d67fc9c) }

var fileDescriptor_00675bbb5d67fc9c = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcf, 0x4f, 0x1b, 0x3b,
	0x10, 0x66, 0x21, 0x24, 0xc4, 0xc9, 0x0b, 0x60, 0xa1, 0xf7, 0x96, 0xa7, 0x47, 0x1e, 0x5d, 0xa9,
	0x2a, 0x97, 0x26, 0x12, 0xbd, 0x54, 0xea, 0x89, 0x96, 0xf2, 0xa3, 0xaa, 0x50, 0xb5, 0xad, 0x7a,
	0xe8, 0x65, 0xe5, 0x5d, 0x0f, 0xac, 0x4b, 0x76, 0xbd, 0xb5, 0xbd, 0x15, 0xe1, 0xd2, 0x7f, 0xa1,
	0x97, 0xde, 0xfa, 0x07, 0xf5, 0xc8, 0xb1, 0xc7, 0x0a, 0xfe, 0x91, 0xca, 0x63, 0x2f, 0x14, 0xc2,
	0x29, 0xf3, 0x7d, 0x33, 0x9e, 0xf9, 0x66, 0xfd, 0xc5, 0xe4, 0xbf, 0x54, 0x9c, 0x67, 0x39, 0x13,
	0xe5, 0xf8, 0x23, 0x2b, 0x18, 0xcb, 0xfd, 0xcf, 0xa8, 0x52, 0xd2, 0x48, 0xba, 0xdc, 0x64, 0x47,
	0x8e, 0xfe, 0x77, 0x3d, 0x93, 0xba, 0x90, 0x3a, 0xc1, 0xf4, 0xd8, 0x01, 0x57, 0x1b, 0x7d, 0x21,
	0xfd, 0x5d, 0x99, 0xd5, 0x05, 0x94, 0xe6, 0x80, 0xe9, 0x9c, 0xae, 0x93, 0x25, 0x2e, 0xb3, 0xc4,
	0x4c, 0x2b, 0x08, 0x83, 0xcd, 0x60, 0xab, 0x1b, 0x77, 0xb8, 0xcc, 0xde, 0x4d, 0x2b, 0xa0, 0x94,
	0xb4, 0x72, 0xa6, 0xf3, 0x70, 0x1e, 0x69, 0x8c, 0xe9, 0xff, 0xa4, 0xa7, 0x8d, 0x54, 0xec, 0x04,
	0x12, 0x05, 0xc7, 0xe1, 0x02, 0xa6, 0x88, 0xa7, 0x62, 0x38, 0xb6, 0x05, 0x75, 0x35, 0x91, 0x8c,
	0x03, 0x4f, 0x98, 0x09, 0x5b, 0xae, 0xa0, 0xa1, 0x76, 0x4c, 0x74, 0x46, 0x56, 0xdf, 0xb3, 0x2c,
	0x13, 0x25, 0x33, 0x42, 0x96, 0x31, 0x64, 0x52, 0x71, 0xfa, 0x80, 0xf4, 0x3f, 0x23, 0x09, 0x49,
	0xc9, 0x8a, 0x46, 0x49, 0xcf, 0x73, 0x47, 0xac, 0x40, 0x35, 0x9c, 0x19, 0x68, 0xd4, 0xd8, 0x98,
	0xfe, 0x4d, 0xda, 0x42, 0xeb, 0x1a, 0x94, 0x17, 0xe2, 0x11, 0x5d, 0x23, 0x8b, 0x29, 0x33, 0x59,
	0xee, 0xc7, 0x3b, 0x10, 0x7d, 0x22, 0x6b, 0xbb, 0x50, 0x31, 0x65, 0x6a, 0x05, 0x07, 0xc2, 0x6a,
	0x9e, 0x1e, 0x1a, 0x28, 0xec, 0x27, 0xa8, 0xd8, 0x29, 0x98, 0x44, 0x70, 0x1c, 0xdc, 0x8a, 0x3b,
	0x88, 0x0f, 0xb9, 0x1d, 0x3a, 0x05, 0xa6, 0x9a, 0xa1, 0x36, 0xb6, 0x43, 0xb5, 0x61, 0xa6, 0xd6,
	0xcd, 0x50, 0x87, 0xae, 0x05, 0xb6, 0x6e, 0x04, 0x46, 0xdf, 0x5a, 0xa4, 0xfd, 0x0a, 0xef, 0x84,
	0x0e, 0xc8, 0xfc, 0x75, 0xff, 0x79, 0x81, 0xad, 0x71, 0x55, 0xdf, 0xda, 0xc6, 0x56, 0x77, 0x95,
	0xcb, 0x12, 0x7c, 0x67, 0x07, 0x2c, 0x0b, 0x05, 0x13, 0x93, 0x66, 0x1b, 0x04, 0x34, 0x24, 0x1d,
	0xc6, 0xb9, 0x02, 0xad, 0xc3, 0x45, 0x77, 0x6f, 0x1e, 0xd2, 0x47, 0x64, 0xb9, 0x62, 0x5a, 0x57,
	0x52, 0x99, 0xa4, 0xac, 0x8b, 0x14, 0x54, 0xd8, 0xc6, 0x8a, 0x41, 0x43, 0x1f, 0x21, 0x4b, 0x37,
	0x08, 0xa9, 0x72, 0x69, 0x64, 0x82, 0xd7, 0xdc, 0xc1, 0x9a, 0x2e, 0x32, 0x68, 0x8d, 0x9b, 0x45,
	0x97, 0x6e, 0x2d, 0xba, 0x42, 0x16, 0xb8, 0xe0, 0x61, 0x17, 0x49, 0x1b, 0x5a, 0x2d, 0x99, 0x02,
	0x66, 0xa4, 0x0a, 0x89, 0xd3, 0xe2, 0x21, 0x7d, 0x46, 0xba, 0xdc, 0xdb, 0x4d, 0x87, 0xbd, 0xcd,
	0x85, 0xad, 0xde, 0xf6, 0xc6, 0xe8, 0x8e, 0x5d, 0x47, 0x7f, 0x1a, 0x32, 0xbe, 0xa9, 0xa7, 0x7b,
	0x8d, 0x2b, 0xd0, 0x2a, 0x3a, 0xec, 0xe3, 0xf9, 0x68, 0xe6, 0xfc, 0x8c, 0x9f, 0xe2, 0x5b, 0xe7,
	0x68, 0x4c, 0x56, 0x79, 0x73, 0xf1, 0x49, 0xee, 0x6e, 0x3e, 0xfc, 0x0b, 0x9b, 0x3d, 0x9c, 0x15,
	0x73, 0x8f, 0x45, 0xe2, 0x15, 0x7e, 0x87, 0xb5, 0xdf, 0x0e, 0x77, 0x74, 0x36, 0x1f, 0xb8, 0x6f,
	0xe7, 0x99, 0x1d, 0x63, 0xd3, 0x75, 0xc5, 0x9b, 0xf4, 0xb2, 0x4b, 0x7b, 0x66, 0xc7, 0x44, 0xdb,
	0xa4, 0xfd, 0x86, 0x29, 0x56, 0x68, 0xba, 0x45, 0x56, 0xce, 0x41, 0xc9, 0xe4, 0x18, 0x20, 0x81,
	0x92, 0xa5, 0x13, 0x70, 0x26, 0x59, 0x8a, 0x07, 0x96, 0xdf, 0x03, 0x78, 0xe9, 0xd8, 0xe8, 0x7b,
	0x40, 0xfa, 0xfb, 0x50, 0x82, 0x16, 0xfa, 0xad, 0xb1, 0xee, 0x7f, 0x4a, 0x7a, 0x4e, 0x73, 0x32,
	0x11, 0xda, 0x84, 0x01, 0x2e, 0xf4, 0xcf, 0xcc, 0x42, 0xce, 0x7f, 0x31, 0x71, 0xf0, 0xb5, 0xd0,
	0xc6, 0xfe, 0xdd, 0xfc, 0xc9, 0x4c, 0xd6, 0xa5, 0x41, 0x0f, 0xb6, 0x62, 0xdf, 0xed, 0x85, 0xa5,
	0xe8, 0x98, 0xb4, 0x2b, 0x54, 0x88, 0x5e, 0xbc, 0xaf, 0xaf, 0x5b, 0x20, 0xf6, 0x65, 0xcf, 0xf7,
	0x7f, 0x5c, 0x0e, 0x83, 0x8b, 0xcb, 0x61, 0xf0, 0xeb, 0x72, 0x18, 0x7c, 0xbd, 0x1a, 0xce, 0x5d,
	0x5c, 0x0d, 0xe7, 0x7e, 0x5e, 0x0d, 0xe7, 0x3e, 0x3c, 0x3e, 0x11, 0x26, 0xaf, 0xd3, 0x51, 0x26,
	0x8b, 0xf1, 0xf5, 0x3b, 0x96, 0x4e, 0x64, 0x76, 0xea, 0xc2, 0xb3, 0xe6, 0x51, 0xb3, 0x8f, 0x90,
	0x4e, 0xdb, 0xf8, 0x50, 0x3d, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x75, 0xa4, 0x3f, 0x37, 0xf4,
	0x04, 0x00, 0x00,
}

func (m *DocumentHash) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DocumentHash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DocumentHash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UploadedAt) > 0 {
		i -= len(m.UploadedAt)
		copy(dAtA[i:], m.UploadedAt)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.UploadedAt)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StorageRef) > 0 {
		i -= len(m.StorageRef)
		copy(dAtA[i:], m.StorageRef)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.StorageRef)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DocType) > 0 {
		i -= len(m.DocType)
		copy(dAtA[i:], m.DocType)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.DocType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VaccinationRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaccinationRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaccinationRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Batch) > 0 {
		i -= len(m.Batch)
		copy(dAtA[i:], m.Batch)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Batch)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VaccineName) > 0 {
		i -= len(m.VaccineName)
		copy(dAtA[i:], m.VaccineName)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.VaccineName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DepartureHistoryItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DepartureHistoryItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DepartureHistoryItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Year) > 0 {
		i -= len(m.Year)
		copy(dAtA[i:], m.Year)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Year)))
		i--
		dAtA[i] = 0x12
	}
	if m.PaketId != 0 {
		i = encodeVarintJamaah(dAtA, i, uint64(m.PaketId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Jamaah) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Jamaah) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Jamaah) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.DepartureHistory) > 0 {
		for iNdEx := len(m.DepartureHistory) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepartureHistory[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintJamaah(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.Vaccinations) > 0 {
		for iNdEx := len(m.Vaccinations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vaccinations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintJamaah(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.Documents) > 0 {
		for iNdEx := len(m.Documents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Documents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintJamaah(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PhotoHash) > 0 {
		i -= len(m.PhotoHash)
		copy(dAtA[i:], m.PhotoHash)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.PhotoHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.PassportNumber) > 0 {
		i -= len(m.PassportNumber)
		copy(dAtA[i:], m.PassportNumber)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.PassportNumber)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Email) > 0 {
		i -= len(m.Email)
		copy(dAtA[i:], m.Email)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Email)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Phone) > 0 {
		i -= len(m.Phone)
		copy(dAtA[i:], m.Phone)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Phone)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintJamaah(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintJamaah(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		i--
		if m.ZeroFeeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintJamaah(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.JamaahCount != 0 {
		i = encodeVarintJamaah(dAtA, i, uint64(m.JamaahCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.JamaahList) > 0 {
		for iNdEx := len(m.JamaahList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.JamaahList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintJamaah(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintJamaah(dAtA []byte, offset int, v uint64) int {
	offset -= sovJamaah(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DocumentHash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DocType)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.StorageRef)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.UploadedAt)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	return n
}

func (m *VaccinationRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VaccineName)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Batch)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	return n
}

func (m *DepartureHistoryItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PaketId != 0 {
		n += 1 + sovJamaah(uint64(m.PaketId))
	}
	l = len(m.Year)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	return n
}

func (m *Jamaah) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovJamaah(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Phone)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.PassportNumber)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.PhotoHash)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	if len(m.Documents) > 0 {
		for _, e := range m.Documents {
			l = e.Size()
			n += 1 + l + sovJamaah(uint64(l))
		}
	}
	if len(m.Vaccinations) > 0 {
		for _, e := range m.Vaccinations {
			l = e.Size()
			n += 1 + l + sovJamaah(uint64(l))
		}
	}
	if len(m.DepartureHistory) > 0 {
		for _, e := range m.DepartureHistory {
			l = e.Size()
			n += 1 + l + sovJamaah(uint64(l))
		}
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovJamaah(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		n += 2
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.JamaahList) > 0 {
		for _, e := range m.JamaahList {
			l = e.Size()
			n += 1 + l + sovJamaah(uint64(l))
		}
	}
	if m.JamaahCount != 0 {
		n += 1 + sovJamaah(uint64(m.JamaahCount))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovJamaah(uint64(l))
	}
	return n
}

func sovJamaah(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozJamaah(x uint64) (n int) {
	return sovJamaah(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DocumentHash) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJamaah
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DocumentHash: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DocumentHash: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StorageRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UploadedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJamaah(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJamaah
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaccinationRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJamaah
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaccinationRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaccinationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaccineName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaccineName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Batch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Batch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJamaah(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJamaah
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DepartureHistoryItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJamaah
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DepartureHistoryItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DepartureHistoryItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaketId", wireType)
			}
			m.PaketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Year", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Year = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJamaah(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJamaah
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Jamaah) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJamaah
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Jamaah: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Jamaah: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PassportNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PassportNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhotoHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhotoHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Documents = append(m.Documents, &DocumentHash{})
			if err := m.Documents[len(m.Documents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vaccinations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vaccinations = append(m.Vaccinations, &VaccinationRecord{})
			if err := m.Vaccinations[len(m.Vaccinations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepartureHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepartureHistory = append(m.DepartureHistory, &DepartureHistoryItem{})
			if err := m.DepartureHistory[len(m.DepartureHistory)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJamaah(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJamaah
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJamaah
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZeroFeeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ZeroFeeEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipJamaah(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJamaah
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJamaah
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JamaahList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JamaahList = append(m.JamaahList, &Jamaah{})
			if err := m.JamaahList[len(m.JamaahList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JamaahCount", wireType)
			}
			m.JamaahCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JamaahCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJamaah
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthJamaah
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipJamaah(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJamaah
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipJamaah(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowJamaah
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJamaah
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthJamaah
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupJamaah
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthJamaah
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthJamaah        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowJamaah          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupJamaah = fmt.Errorf("proto: unexpected end of group")
)
