// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bizchain/paket/paket.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Review represents a rating/review for a paket (marketplace)
type Review struct {
	Reviewer  string `protobuf:"bytes,1,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
	Rating    uint32 `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment   string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_df88d69655309e6e, []int{0}
}
func (m *Review) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Review.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return m.Size()
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetReviewer() string {
	if m != nil {
		return m.Reviewer
	}
	return ""
}

func (m *Review) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Review) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Review) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

// Paket represents a Hajj/Umroh package (smart contract paket)
type Paket struct {
	Id            uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string    `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Schedule      string    `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Quota         uint64    `protobuf:"varint,5,opt,name=quota,proto3" json:"quota,omitempty"`
	Booked        uint64    `protobuf:"varint,6,opt,name=booked,proto3" json:"booked,omitempty"`
	Hotel         string    `protobuf:"bytes,7,opt,name=hotel,proto3" json:"hotel,omitempty"`
	Airline       string    `protobuf:"bytes,8,opt,name=airline,proto3" json:"airline,omitempty"`
	Muthawif      string    `protobuf:"bytes,9,opt,name=muthawif,proto3" json:"muthawif,omitempty"`
	Status        string    `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	DepartureDate string    `protobuf:"bytes,11,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	ReturnDate    string    `protobuf:"bytes,12,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	Category      string    `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
	Description   string    `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string    `protobuf:"bytes,15,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Reviews       []*Review `protobuf:"bytes,16,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Creator       string    `protobuf:"bytes,17,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt     string    `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string    `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Paket) Reset()         { *m = Paket{} }
func (m *Paket) String() string { return proto.CompactTextString(m) }
func (*Paket) ProtoMessage()    {}
func (*Paket) Descriptor() ([]byte, []int) {
	return fileDescriptor_df88d69655309e6e, []int{1}
}
func (m *Paket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Paket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Paket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Paket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paket.Merge(m, src)
}
func (m *Paket) XXX_Size() int {
	return m.Size()
}
func (m *Paket) XXX_DiscardUnknown() {
	xxx_messageInfo_Paket.DiscardUnknown(m)
}

var xxx_messageInfo_Paket proto.InternalMessageInfo

func (m *Paket) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Paket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Paket) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Paket) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

func (m *Paket) GetQuota() uint64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *Paket) GetBooked() uint64 {
	if m != nil {
		return m.Booked
	}
	return 0
}

func (m *Paket) GetHotel() string {
	if m != nil {
		return m.Hotel
	}
	return ""
}

func (m *Paket) GetAirline() string {
	if m != nil {
		return m.Airline
	}
	return ""
}

func (m *Paket) GetMuthawif() string {
	if m != nil {
		return m.Muthawif
	}
	return ""
}

func (m *Paket) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Paket) GetDepartureDate() string {
	if m != nil {
		return m.DepartureDate
	}
	return ""
}

func (m *Paket) GetReturnDate() string {
	if m != nil {
		return m.ReturnDate
	}
	return ""
}

func (m *Paket) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Paket) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Paket) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Paket) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *Paket) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Paket) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Paket) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Params defines the parameters for the paket module
type Params struct {
	ZeroFeeEnabled bool `protobuf:"varint,1,opt,name=zero_fee_enabled,json=zeroFeeEnabled,proto3" json:"zero_fee_enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_df88d69655309e6e, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetZeroFeeEnabled() bool {
	if m != nil {
		return m.ZeroFeeEnabled
	}
	return false
}

// GenesisState defines the genesis state of the paket module
type GenesisState struct {
	PaketList  []*Paket `protobuf:"bytes,1,rep,name=paket_list,json=paketList,proto3" json:"paket_list,omitempty"`
	PaketCount uint64   `protobuf:"varint,2,opt,name=paket_count,json=paketCount,proto3" json:"paket_count,omitempty"`
	Params     *Params  `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_df88d69655309e6e, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPaketList() []*Paket {
	if m != nil {
		return m.PaketList
	}
	return nil
}

func (m *GenesisState) GetPaketCount() uint64 {
	if m != nil {
		return m.PaketCount
	}
	return 0
}

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*Review)(nil), "bizchain.paket.Review")
	proto.RegisterType((*Paket)(nil), "bizchain.paket.Paket")
	proto.RegisterType((*Params)(nil), "bizchain.paket.Params")
	proto.RegisterType((*GenesisState)(nil), "bizchain.paket.GenesisState")
}

func init() { proto.RegisterFile("bizchain/paket/paket.proto", fileDescriptor_df88d69655309e6e) }

var fileDescriptor_df88d69655309e6e = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0xdb, 0x24, 0x4d, 0x26, 0x6d, 0x28, 0x0b, 0x54, 0x4b, 0x10, 0x21, 0x8a, 0x40, 0xca,
	0x01, 0x52, 0x54, 0xf8, 0x81, 0x16, 0x28, 0x42, 0xe2, 0x50, 0x19, 0x71, 0xe1, 0x62, 0x6d, 0xec,
	0x69, 0xb2, 0xaa, 0xed, 0x35, 0xeb, 0x31, 0xa5, 0xfd, 0x0a, 0x2e, 0xfc, 0x05, 0x47, 0x3e, 0x82,
	0x63, 0xc5, 0x89, 0x23, 0x6a, 0x7f, 0x04, 0xed, 0xac, 0x13, 0x41, 0xc4, 0xc5, 0xda, 0xf7, 0xde,
	0xac, 0xdf, 0xcc, 0xee, 0x5b, 0xe8, 0x4f, 0xf5, 0x45, 0x3c, 0x57, 0x3a, 0xdf, 0x2b, 0xd4, 0x29,
	0x92, 0xff, 0x4e, 0x0a, 0x6b, 0xc8, 0x88, 0xde, 0x42, 0x9b, 0x30, 0xdb, 0xbf, 0x1b, 0x9b, 0x32,
	0x33, 0x65, 0xc4, 0xea, 0x9e, 0x07, 0xbe, 0x74, 0x54, 0x41, 0x2b, 0xc4, 0x4f, 0x1a, 0xcf, 0x44,
	0x1f, 0xda, 0x96, 0x57, 0x68, 0x65, 0x30, 0x0c, 0xc6, 0x9d, 0x70, 0x89, 0xc5, 0x2e, 0xb4, 0xac,
	0x22, 0x9d, 0xcf, 0xe4, 0xfa, 0x30, 0x18, 0x6f, 0x87, 0x35, 0x12, 0x12, 0x36, 0x63, 0x93, 0x65,
	0x98, 0x93, 0xdc, 0xe0, 0x2d, 0x0b, 0x28, 0xee, 0x03, 0xc4, 0x16, 0x15, 0x61, 0x12, 0x29, 0x92,
	0x0d, 0x16, 0x3b, 0x35, 0x73, 0x40, 0xa3, 0x6f, 0x0d, 0x68, 0x1e, 0xbb, 0xde, 0x44, 0x0f, 0xd6,
	0x75, 0xc2, 0x86, 0x8d, 0x70, 0x5d, 0x27, 0x42, 0x40, 0x23, 0x57, 0x19, 0xb2, 0x51, 0x27, 0xe4,
	0xb5, 0x78, 0x08, 0xcd, 0xc2, 0xea, 0x18, 0xbd, 0xc9, 0x61, 0xef, 0xe7, 0xf7, 0x27, 0x50, 0x4f,
	0xf1, 0x26, 0xa7, 0xd0, 0x8b, 0x6e, 0x80, 0x32, 0x9e, 0x63, 0x52, 0xa5, 0x58, 0x1b, 0x2e, 0xb1,
	0xb8, 0x0d, 0xcd, 0x8f, 0x95, 0x21, 0x25, 0x9b, 0x6c, 0xe4, 0x81, 0x1b, 0x6b, 0x6a, 0xcc, 0x29,
	0x26, 0xb2, 0xc5, 0x74, 0x8d, 0x5c, 0xf5, 0xdc, 0x10, 0xa6, 0x72, 0x93, 0x7f, 0xe3, 0x81, 0x1b,
	0x56, 0x69, 0x9b, 0xea, 0x1c, 0x65, 0xdb, 0x0f, 0x5b, 0x43, 0xe7, 0x9c, 0x55, 0x34, 0x57, 0x67,
	0xfa, 0x44, 0x76, 0xbc, 0xf3, 0x02, 0x3b, 0x8f, 0x92, 0x14, 0x55, 0xa5, 0x04, 0x56, 0x6a, 0x24,
	0x1e, 0x41, 0x2f, 0xc1, 0x42, 0x59, 0xaa, 0x2c, 0x46, 0x89, 0x22, 0x94, 0x5d, 0xd6, 0xb7, 0x97,
	0xec, 0x4b, 0x45, 0x28, 0x1e, 0x40, 0xd7, 0x22, 0x55, 0x36, 0xf7, 0x35, 0x5b, 0x5c, 0x03, 0x9e,
	0xe2, 0x82, 0x3e, 0xb4, 0x63, 0x45, 0x38, 0x33, 0xf6, 0x5c, 0x6e, 0x7b, 0xef, 0x05, 0x16, 0x43,
	0xe8, 0x26, 0x58, 0xc6, 0x56, 0x17, 0xa4, 0x4d, 0x2e, 0x7b, 0x2c, 0xff, 0x4d, 0x89, 0x7b, 0xd0,
	0xd1, 0x99, 0x9a, 0x61, 0x54, 0xd9, 0x54, 0xde, 0xf0, 0xdb, 0x99, 0x78, 0x6f, 0x53, 0xf1, 0x14,
	0x36, 0x7d, 0x02, 0x4a, 0xb9, 0x33, 0xdc, 0x18, 0x77, 0xf7, 0x77, 0x27, 0xff, 0x06, 0x6b, 0xe2,
	0xa3, 0x13, 0x2e, 0xca, 0x38, 0x0f, 0xee, 0x8e, 0x8d, 0x95, 0x37, 0xeb, 0x3c, 0x78, 0xb8, 0x92,
	0x07, 0xb1, 0x92, 0x07, 0x27, 0x57, 0x45, 0xb2, 0x90, 0x6f, 0x79, 0xb9, 0x66, 0x0e, 0x68, 0xb4,
	0x0f, 0xad, 0x63, 0x65, 0x55, 0x56, 0x8a, 0x31, 0xec, 0x5c, 0xa0, 0x35, 0xd1, 0x09, 0x62, 0x84,
	0xb9, 0x9a, 0xa6, 0xe8, 0xc3, 0xd3, 0x0e, 0x7b, 0x8e, 0x3f, 0x42, 0x7c, 0xe5, 0xd9, 0xd1, 0xd7,
	0x00, 0xb6, 0x5e, 0x63, 0x8e, 0xa5, 0x2e, 0xdf, 0x91, 0x3b, 0xa9, 0xe7, 0x00, 0xdc, 0x75, 0x94,
	0xea, 0x92, 0x64, 0xc0, 0x13, 0xdd, 0x59, 0x9d, 0x88, 0x43, 0x19, 0x76, 0x18, 0xbc, 0xd5, 0x25,
	0xb9, 0x0b, 0xf0, 0xbb, 0x62, 0x53, 0xe5, 0xc4, 0xb1, 0x6c, 0x84, 0xfe, 0x47, 0x2f, 0x1c, 0x23,
	0x26, 0xd0, 0x2a, 0xb8, 0x37, 0x4e, 0xe7, 0x7f, 0x0e, 0xc9, 0x77, 0x1e, 0xd6, 0x55, 0x87, 0x47,
	0x3f, 0xae, 0x06, 0xc1, 0xe5, 0xd5, 0x20, 0xf8, 0x7d, 0x35, 0x08, 0xbe, 0x5c, 0x0f, 0xd6, 0x2e,
	0xaf, 0x07, 0x6b, 0xbf, 0xae, 0x07, 0x6b, 0x1f, 0x1e, 0xcf, 0x34, 0xcd, 0xab, 0xe9, 0x24, 0x36,
	0xd9, 0xde, 0xf2, 0x75, 0x4f, 0x53, 0x13, 0x9f, 0xfa, 0xe5, 0xe7, 0xfa, 0xa9, 0xd3, 0x79, 0x81,
	0xe5, 0xb4, 0xc5, 0x0f, 0xf8, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xeb, 0xbe, 0xfc,
	0x09, 0x04, 0x00, 0x00,
}

func (m *Review) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Review) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Review) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Comment) > 0 {
		i -= len(m.Comment)
		copy(dAtA[i:], m.Comment)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Comment)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Rating != 0 {
		i = encodeVarintPaket(dAtA, i, uint64(m.Rating))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Reviewer) > 0 {
		i -= len(m.Reviewer)
		copy(dAtA[i:], m.Reviewer)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Reviewer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Paket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Paket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Paket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.Reviews) > 0 {
		for iNdEx := len(m.Reviews) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reviews[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPaket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.ImageUrl) > 0 {
		i -= len(m.ImageUrl)
		copy(dAtA[i:], m.ImageUrl)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.ImageUrl)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.ReturnDate) > 0 {
		i -= len(m.ReturnDate)
		copy(dAtA[i:], m.ReturnDate)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.ReturnDate)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.DepartureDate) > 0 {
		i -= len(m.DepartureDate)
		copy(dAtA[i:], m.DepartureDate)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.DepartureDate)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Muthawif) > 0 {
		i -= len(m.Muthawif)
		copy(dAtA[i:], m.Muthawif)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Muthawif)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Airline) > 0 {
		i -= len(m.Airline)
		copy(dAtA[i:], m.Airline)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Airline)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Hotel) > 0 {
		i -= len(m.Hotel)
		copy(dAtA[i:], m.Hotel)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Hotel)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Booked != 0 {
		i = encodeVarintPaket(dAtA, i, uint64(m.Booked))
		i--
		dAtA[i] = 0x30
	}
	if m.Quota != 0 {
		i = encodeVarintPaket(dAtA, i, uint64(m.Quota))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Schedule) > 0 {
		i -= len(m.Schedule)
		copy(dAtA[i:], m.Schedule)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Schedule)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPaket(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintPaket(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		i--
		if m.ZeroFeeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPaket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.PaketCount != 0 {
		i = encodeVarintPaket(dAtA, i, uint64(m.PaketCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PaketList) > 0 {
		for iNdEx := len(m.PaketList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PaketList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPaket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPaket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPaket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Review) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reviewer)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	if m.Rating != 0 {
		n += 1 + sovPaket(uint64(m.Rating))
	}
	l = len(m.Comment)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	return n
}

func (m *Paket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPaket(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.Schedule)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	if m.Quota != 0 {
		n += 1 + sovPaket(uint64(m.Quota))
	}
	if m.Booked != 0 {
		n += 1 + sovPaket(uint64(m.Booked))
	}
	l = len(m.Hotel)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.Airline)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.Muthawif)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.DepartureDate)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.ReturnDate)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	l = len(m.ImageUrl)
	if l > 0 {
		n += 1 + l + sovPaket(uint64(l))
	}
	if len(m.Reviews) > 0 {
		for _, e := range m.Reviews {
			l = e.Size()
			n += 2 + l + sovPaket(uint64(l))
		}
	}
	l = len(m.Creator)
	if l > 0 {
		n += 2 + l + sovPaket(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 2 + l + sovPaket(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 2 + l + sovPaket(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		n += 2
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PaketList) > 0 {
		for _, e := range m.PaketList {
			l = e.Size()
			n += 1 + l + sovPaket(uint64(l))
		}
	}
	if m.PaketCount != 0 {
		n += 1 + sovPaket(uint64(m.PaketCount))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovPaket(uint64(l))
	}
	return n
}

func sovPaket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPaket(x uint64) (n int) {
	return sovPaket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Review) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPaket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Review: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Review: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reviewer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reviewer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rating", wireType)
			}
			m.Rating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPaket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPaket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Paket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPaket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Paket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Paket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Schedule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Schedule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quota", wireType)
			}
			m.Quota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quota |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Booked", wireType)
			}
			m.Booked = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Booked |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hotel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hotel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Airline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Airline = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Muthawif", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Muthawif = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepartureDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepartureDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReturnDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReturnDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reviews", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reviews = append(m.Reviews, &Review{})
			if err := m.Reviews[len(m.Reviews)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPaket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPaket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPaket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZeroFeeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ZeroFeeEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPaket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPaket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPaket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaketList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaketList = append(m.PaketList, &Paket{})
			if err := m.PaketList[len(m.PaketList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaketCount", wireType)
			}
			m.PaketCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaketCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPaket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPaket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPaket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPaket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPaket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPaket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPaket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPaket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPaket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPaket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPaket = fmt.Errorf("proto: unexpected end of group")
)
