// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bizchain/referral/referral.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Referral represents an on-chain referral relationship
type Referral struct {
	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Agent          string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	ReferredJamaah string `protobuf:"bytes,3,opt,name=referred_jamaah,json=referredJamaah,proto3" json:"referred_jamaah,omitempty"`
	PaketId        uint64 `protobuf:"varint,4,opt,name=paket_id,json=paketId,proto3" json:"paket_id,omitempty"`
	CommissionRate string `protobuf:"bytes,5,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	Commission     string `protobuf:"bytes,6,opt,name=commission,proto3" json:"commission,omitempty"`
	Status         string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaidAt         string `protobuf:"bytes,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	Creator        string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt      string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Referral) Reset()         { *m = Referral{} }
func (m *Referral) String() string { return proto.CompactTextString(m) }
func (*Referral) ProtoMessage()    {}
func (*Referral) Descriptor() ([]byte, []int) {
	return fileDescriptor_581ee3c6f231ea7c, []int{0}
}
func (m *Referral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Referral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Referral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Referral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Referral.Merge(m, src)
}
func (m *Referral) XXX_Size() int {
	return m.Size()
}
func (m *Referral) XXX_DiscardUnknown() {
	xxx_messageInfo_Referral.DiscardUnknown(m)
}

var xxx_messageInfo_Referral proto.InternalMessageInfo

func (m *Referral) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Referral) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *Referral) GetReferredJamaah() string {
	if m != nil {
		return m.ReferredJamaah
	}
	return ""
}

func (m *Referral) GetPaketId() uint64 {
	if m != nil {
		return m.PaketId
	}
	return 0
}

func (m *Referral) GetCommissionRate() string {
	if m != nil {
		return m.CommissionRate
	}
	return ""
}

func (m *Referral) GetCommission() string {
	if m != nil {
		return m.Commission
	}
	return ""
}

func (m *Referral) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Referral) GetPaidAt() string {
	if m != nil {
		return m.PaidAt
	}
	return ""
}

func (m *Referral) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Referral) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

// Params defines the parameters for the referral module
type Params struct {
	ZeroFeeEnabled        bool   `protobuf:"varint,1,opt,name=zero_fee_enabled,json=zeroFeeEnabled,proto3" json:"zero_fee_enabled,omitempty"`
	DefaultCommissionRate string `protobuf:"bytes,2,opt,name=default_commission_rate,json=defaultCommissionRate,proto3" json:"default_commission_rate,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_581ee3c6f231ea7c, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetZeroFeeEnabled() bool {
	if m != nil {
		return m.ZeroFeeEnabled
	}
	return false
}

func (m *Params) GetDefaultCommissionRate() string {
	if m != nil {
		return m.DefaultCommissionRate
	}
	return ""
}

// GenesisState defines the genesis state of the referral module
type GenesisState struct {
	ReferralList  []*Referral `protobuf:"bytes,1,rep,name=referral_list,json=referralList,proto3" json:"referral_list,omitempty"`
	ReferralCount uint64      `protobuf:"varint,2,opt,name=referral_count,json=referralCount,proto3" json:"referral_count,omitempty"`
	Params        *Params     `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_581ee3c6f231ea7c, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetReferralList() []*Referral {
	if m != nil {
		return m.ReferralList
	}
	return nil
}

func (m *GenesisState) GetReferralCount() uint64 {
	if m != nil {
		return m.ReferralCount
	}
	return 0
}

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*Referral)(nil), "bizchain.referral.Referral")
	proto.RegisterType((*Params)(nil), "bizchain.referral.Params")
	proto.RegisterType((*GenesisState)(nil), "bizchain.referral.GenesisState")
}

func init() { proto.RegisterFile("bizchain/referral/referral.proto", fileDescriptor_581ee3c6f231ea7c) }

var fileDescriptor_581ee3c6f231ea7c = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x14, 0x8c, 0xd3, 0xd4, 0x49, 0x5e, 0x8b, 0x0b, 0x2b, 0xa0, 0x1b, 0x10, 0x56, 0x14, 0x09, 0x91,
	0x0b, 0x8e, 0x28, 0x07, 0xae, 0xb4, 0x15, 0x45, 0x41, 0x1c, 0x90, 0xb9, 0x71, 0xb1, 0xd6, 0xf6,
	0x4b, 0xb3, 0xd4, 0xf6, 0x5a, 0xde, 0x17, 0x09, 0xf2, 0x15, 0x7c, 0x07, 0x67, 0xfe, 0x01, 0x8e,
	0x15, 0x27, 0x8e, 0x28, 0xf9, 0x11, 0xe4, 0xb5, 0x9d, 0x00, 0xcd, 0xed, 0xcd, 0xbc, 0xf1, 0x78,
	0x77, 0x76, 0x60, 0x18, 0xca, 0x65, 0x34, 0x17, 0x32, 0x9b, 0x14, 0x38, 0xc3, 0xa2, 0x10, 0xc9,
	0x66, 0xf0, 0xf2, 0x42, 0x91, 0x62, 0x77, 0x1a, 0x85, 0xd7, 0x2c, 0x1e, 0x0c, 0x22, 0xa5, 0x53,
	0xa5, 0x03, 0x23, 0x98, 0x54, 0xa0, 0x52, 0x8f, 0xbe, 0xb7, 0xa1, 0xe7, 0xd7, 0x3a, 0xe6, 0x40,
	0x5b, 0xc6, 0xdc, 0x1a, 0x5a, 0xe3, 0x8e, 0xdf, 0x96, 0x31, 0xbb, 0x0b, 0xfb, 0xe2, 0x12, 0x33,
	0xe2, 0xed, 0xa1, 0x35, 0xee, 0xfb, 0x15, 0x60, 0x4f, 0xe0, 0xa8, 0x72, 0xc6, 0x38, 0xf8, 0x28,
	0x52, 0x21, 0xe6, 0x7c, 0xcf, 0xec, 0x9d, 0x86, 0x7e, 0x63, 0x58, 0x36, 0x80, 0x5e, 0x2e, 0xae,
	0x90, 0x02, 0x19, 0xf3, 0x8e, 0x31, 0xed, 0x1a, 0x3c, 0x8d, 0xd9, 0x0b, 0x38, 0x8a, 0x54, 0x9a,
	0x4a, 0xad, 0xa5, 0xca, 0x82, 0x42, 0x10, 0xf2, 0xfd, 0xd2, 0xe3, 0xcc, 0xf9, 0xf9, 0xed, 0x29,
	0xd4, 0x27, 0x9c, 0x66, 0xe4, 0x3b, 0x5b, 0x99, 0x2f, 0x08, 0x99, 0x07, 0xb0, 0x65, 0xb8, 0xbd,
	0xf3, 0x9b, 0xbf, 0x14, 0xec, 0x3e, 0xd8, 0x9a, 0x04, 0x2d, 0x34, 0xef, 0x9a, 0x33, 0xd6, 0x88,
	0x1d, 0x43, 0x37, 0x17, 0x32, 0x0e, 0x04, 0xf1, 0x5e, 0xb5, 0x28, 0xe1, 0x29, 0x31, 0x0e, 0xdd,
	0xa8, 0x40, 0x41, 0xaa, 0xe0, 0x7d, 0xb3, 0x68, 0x20, 0x7b, 0x04, 0x60, 0x46, 0x34, 0x5f, 0x81,
	0x59, 0xf6, 0x6b, 0xe6, 0x94, 0x46, 0x4b, 0xb0, 0xdf, 0x89, 0x42, 0xa4, 0x9a, 0x8d, 0xe1, 0xf6,
	0x12, 0x0b, 0x15, 0xcc, 0x10, 0x03, 0xcc, 0x44, 0x98, 0x60, 0x15, 0x6a, 0xcf, 0x77, 0x4a, 0xfe,
	0x02, 0xf1, 0x55, 0xc5, 0xb2, 0x0b, 0x38, 0x8e, 0x71, 0x26, 0x16, 0x09, 0x05, 0xff, 0xc7, 0xd1,
	0xde, 0x79, 0xb5, 0x7b, 0xb5, 0xfc, 0xfc, 0x9f, 0x54, 0x46, 0x5f, 0x2d, 0x38, 0x7c, 0x8d, 0x19,
	0x6a, 0xa9, 0xdf, 0x53, 0x19, 0xd3, 0x4b, 0xb8, 0xd5, 0xbc, 0x7e, 0x90, 0x48, 0x4d, 0xdc, 0x1a,
	0xee, 0x8d, 0x0f, 0x4e, 0x1e, 0x7a, 0x37, 0xca, 0xe1, 0x35, 0xaf, 0xef, 0x1f, 0x36, 0xd4, 0x5b,
	0xa9, 0x89, 0x3d, 0x06, 0x67, 0xe3, 0x10, 0xa9, 0x45, 0x5d, 0x82, 0x8e, 0xbf, 0xf1, 0x3d, 0x2f,
	0x49, 0xf6, 0x0c, 0xec, 0xdc, 0xdc, 0xda, 0x74, 0xe0, 0xe0, 0x64, 0xb0, 0xe3, 0x0f, 0x55, 0x2c,
	0x7e, 0x2d, 0x3c, 0x9b, 0xfe, 0x58, 0xb9, 0xd6, 0xf5, 0xca, 0xb5, 0x7e, 0xaf, 0x5c, 0xeb, 0xcb,
	0xda, 0x6d, 0x5d, 0xaf, 0xdd, 0xd6, 0xaf, 0xb5, 0xdb, 0xfa, 0x30, 0xb9, 0x94, 0x34, 0x5f, 0x84,
	0x5e, 0xa4, 0xd2, 0xc9, 0xa6, 0xe7, 0x61, 0xa2, 0xa2, 0xab, 0x6a, 0xfc, 0xb4, 0x2d, 0x3d, 0x7d,
	0xce, 0x51, 0x87, 0xb6, 0x29, 0xf1, 0xf3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x50, 0xea,
	0x87, 0x16, 0x03, 0x00, 0x00,
}

func (m *Referral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Referral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Referral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.PaidAt) > 0 {
		i -= len(m.PaidAt)
		copy(dAtA[i:], m.PaidAt)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.PaidAt)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Commission) > 0 {
		i -= len(m.Commission)
		copy(dAtA[i:], m.Commission)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.Commission)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CommissionRate) > 0 {
		i -= len(m.CommissionRate)
		copy(dAtA[i:], m.CommissionRate)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.CommissionRate)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PaketId != 0 {
		i = encodeVarintReferral(dAtA, i, uint64(m.PaketId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ReferredJamaah) > 0 {
		i -= len(m.ReferredJamaah)
		copy(dAtA[i:], m.ReferredJamaah)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.ReferredJamaah)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Agent) > 0 {
		i -= len(m.Agent)
		copy(dAtA[i:], m.Agent)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.Agent)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintReferral(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DefaultCommissionRate) > 0 {
		i -= len(m.DefaultCommissionRate)
		copy(dAtA[i:], m.DefaultCommissionRate)
		i = encodeVarintReferral(dAtA, i, uint64(len(m.DefaultCommissionRate)))
		i--
		dAtA[i] = 0x12
	}
	if m.ZeroFeeEnabled {
		i--
		if m.ZeroFeeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReferral(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ReferralCount != 0 {
		i = encodeVarintReferral(dAtA, i, uint64(m.ReferralCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ReferralList) > 0 {
		for iNdEx := len(m.ReferralList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReferralList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintReferral(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintReferral(dAtA []byte, offset int, v uint64) int {
	offset -= sovReferral(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Referral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovReferral(uint64(m.Id))
	}
	l = len(m.Agent)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	l = len(m.ReferredJamaah)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	if m.PaketId != 0 {
		n += 1 + sovReferral(uint64(m.PaketId))
	}
	l = len(m.CommissionRate)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	l = len(m.Commission)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	l = len(m.PaidAt)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		n += 2
	}
	l = len(m.DefaultCommissionRate)
	if l > 0 {
		n += 1 + l + sovReferral(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ReferralList) > 0 {
		for _, e := range m.ReferralList {
			l = e.Size()
			n += 1 + l + sovReferral(uint64(l))
		}
	}
	if m.ReferralCount != 0 {
		n += 1 + sovReferral(uint64(m.ReferralCount))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovReferral(uint64(l))
	}
	return n
}

func sovReferral(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReferral(x uint64) (n int) {
	return sovReferral(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Referral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReferral
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Referral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Referral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferredJamaah", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferredJamaah = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaketId", wireType)
			}
			m.PaketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissionRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommissionRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commission = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaidAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaidAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReferral(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReferral
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReferral
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZeroFeeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ZeroFeeEnabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultCommissionRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultCommissionRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReferral(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReferral
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReferral
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferralList = append(m.ReferralList, &Referral{})
			if err := m.ReferralList[len(m.ReferralList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralCount", wireType)
			}
			m.ReferralCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReferralCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReferral
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReferral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReferral(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReferral
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReferral(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReferral
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReferral
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReferral
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReferral
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReferral
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReferral        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReferral          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReferral = fmt.Errorf("proto: unexpected end of group")
)
