// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bizchain/audit/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLogAction struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Module   string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Action   string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Actor    string `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	TargetId string `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DataHash string `protobuf:"bytes,6,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	Metadata string `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *MsgLogAction) Reset()         { *m = MsgLogAction{} }
func (m *MsgLogAction) String() string { return proto.CompactTextString(m) }
func (*MsgLogAction) ProtoMessage()    {}
func (*MsgLogAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{0}
}
func (m *MsgLogAction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLogAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLogAction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLogAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLogAction.Merge(m, src)
}
func (m *MsgLogAction) XXX_Size() int {
	return m.Size()
}
func (m *MsgLogAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLogAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLogAction proto.InternalMessageInfo

func (m *MsgLogAction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgLogAction) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *MsgLogAction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MsgLogAction) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *MsgLogAction) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *MsgLogAction) GetDataHash() string {
	if m != nil {
		return m.DataHash
	}
	return ""
}

func (m *MsgLogAction) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type MsgLogActionResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgLogActionResponse) Reset()         { *m = MsgLogActionResponse{} }
func (m *MsgLogActionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLogActionResponse) ProtoMessage()    {}
func (*MsgLogActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{1}
}
func (m *MsgLogActionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLogActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLogActionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLogActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLogActionResponse.Merge(m, src)
}
func (m *MsgLogActionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLogActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLogActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLogActionResponse proto.InternalMessageInfo

func (m *MsgLogActionResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetAuditLogRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetAuditLogRequest) Reset()         { *m = QueryGetAuditLogRequest{} }
func (m *QueryGetAuditLogRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuditLogRequest) ProtoMessage()    {}
func (*QueryGetAuditLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{2}
}
func (m *QueryGetAuditLogRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuditLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuditLogRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuditLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuditLogRequest.Merge(m, src)
}
func (m *QueryGetAuditLogRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuditLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuditLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuditLogRequest proto.InternalMessageInfo

func (m *QueryGetAuditLogRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetAuditLogResponse struct {
	AuditLog *AuditLog `protobuf:"bytes,1,opt,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
}

func (m *QueryGetAuditLogResponse) Reset()         { *m = QueryGetAuditLogResponse{} }
func (m *QueryGetAuditLogResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuditLogResponse) ProtoMessage()    {}
func (*QueryGetAuditLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{3}
}
func (m *QueryGetAuditLogResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuditLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuditLogResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuditLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuditLogResponse.Merge(m, src)
}
func (m *QueryGetAuditLogResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuditLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuditLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuditLogResponse proto.InternalMessageInfo

func (m *QueryGetAuditLogResponse) GetAuditLog() *AuditLog {
	if m != nil {
		return m.AuditLog
	}
	return nil
}

type QueryAllAuditLogRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuditLogRequest) Reset()         { *m = QueryAllAuditLogRequest{} }
func (m *QueryAllAuditLogRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuditLogRequest) ProtoMessage()    {}
func (*QueryAllAuditLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{4}
}
func (m *QueryAllAuditLogRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuditLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuditLogRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuditLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuditLogRequest.Merge(m, src)
}
func (m *QueryAllAuditLogRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuditLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuditLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuditLogRequest proto.InternalMessageInfo

func (m *QueryAllAuditLogRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAuditLogResponse struct {
	AuditLog   []*AuditLog         `protobuf:"bytes,1,rep,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuditLogResponse) Reset()         { *m = QueryAllAuditLogResponse{} }
func (m *QueryAllAuditLogResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuditLogResponse) ProtoMessage()    {}
func (*QueryAllAuditLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{5}
}
func (m *QueryAllAuditLogResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuditLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuditLogResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuditLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuditLogResponse.Merge(m, src)
}
func (m *QueryAllAuditLogResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuditLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuditLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuditLogResponse proto.InternalMessageInfo

func (m *QueryAllAuditLogResponse) GetAuditLog() []*AuditLog {
	if m != nil {
		return m.AuditLog
	}
	return nil
}

func (m *QueryAllAuditLogResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAuditLogByModuleRequest struct {
	Module     string             `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAuditLogByModuleRequest) Reset()         { *m = QueryAuditLogByModuleRequest{} }
func (m *QueryAuditLogByModuleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuditLogByModuleRequest) ProtoMessage()    {}
func (*QueryAuditLogByModuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{6}
}
func (m *QueryAuditLogByModuleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditLogByModuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditLogByModuleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditLogByModuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditLogByModuleRequest.Merge(m, src)
}
func (m *QueryAuditLogByModuleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditLogByModuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditLogByModuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditLogByModuleRequest proto.InternalMessageInfo

func (m *QueryAuditLogByModuleRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *QueryAuditLogByModuleRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAuditLogByModuleResponse struct {
	AuditLog   []*AuditLog         `protobuf:"bytes,1,rep,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAuditLogByModuleResponse) Reset()         { *m = QueryAuditLogByModuleResponse{} }
func (m *QueryAuditLogByModuleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuditLogByModuleResponse) ProtoMessage()    {}
func (*QueryAuditLogByModuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60bcb596e1566f7, []int{7}
}
func (m *QueryAuditLogByModuleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditLogByModuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditLogByModuleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditLogByModuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditLogByModuleResponse.Merge(m, src)
}
func (m *QueryAuditLogByModuleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditLogByModuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditLogByModuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditLogByModuleResponse proto.InternalMessageInfo

func (m *QueryAuditLogByModuleResponse) GetAuditLog() []*AuditLog {
	if m != nil {
		return m.AuditLog
	}
	return nil
}

func (m *QueryAuditLogByModuleResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgLogAction)(nil), "bizchain.audit.MsgLogAction")
	proto.RegisterType((*MsgLogActionResponse)(nil), "bizchain.audit.MsgLogActionResponse")
	proto.RegisterType((*QueryGetAuditLogRequest)(nil), "bizchain.audit.QueryGetAuditLogRequest")
	proto.RegisterType((*QueryGetAuditLogResponse)(nil), "bizchain.audit.QueryGetAuditLogResponse")
	proto.RegisterType((*QueryAllAuditLogRequest)(nil), "bizchain.audit.QueryAllAuditLogRequest")
	proto.RegisterType((*QueryAllAuditLogResponse)(nil), "bizchain.audit.QueryAllAuditLogResponse")
	proto.RegisterType((*QueryAuditLogByModuleRequest)(nil), "bizchain.audit.QueryAuditLogByModuleRequest")
	proto.RegisterType((*QueryAuditLogByModuleResponse)(nil), "bizchain.audit.QueryAuditLogByModuleResponse")
}

func init() { proto.RegisterFile("bizchain/audit/tx.proto", fileDescriptor_c60bcb596e1566f7) }

var fileDescriptor_c60bcb596e1566f7 = []byte{
	// 639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xef, 0x25, 0x6d, 0x9a, 0x5c, 0x51, 0x85, 0x4e, 0x15, 0x75, 0xdd, 0x60, 0x15, 0x0b, 0xa5,
	0x05, 0x05, 0x9f, 0x1a, 0xe0, 0x03, 0xa4, 0x43, 0x0a, 0x52, 0x23, 0x68, 0x06, 0x06, 0x96, 0xe8,
	0x6c, 0x9f, 0x1c, 0x0b, 0xc7, 0x97, 0xc6, 0x17, 0xd4, 0x50, 0x95, 0x01, 0xc4, 0x8e, 0xc4, 0xc6,
	0xc2, 0xc4, 0xc7, 0x60, 0x63, 0x60, 0xac, 0xc4, 0xc2, 0x88, 0x12, 0x3e, 0x08, 0xf2, 0xdd, 0x99,
	0xfc, 0xb3, 0x69, 0xc5, 0xc4, 0x92, 0xf8, 0xbd, 0xdf, 0xfb, 0xf3, 0x7b, 0xcf, 0xbf, 0x3b, 0xc3,
	0x4d, 0xdb, 0x7f, 0xe5, 0x74, 0x88, 0x1f, 0x62, 0x32, 0x70, 0x7d, 0x8e, 0xf9, 0xa9, 0xd5, 0xeb,
	0x33, 0xce, 0xd0, 0x7a, 0x02, 0x58, 0x02, 0xd0, 0xb7, 0x1c, 0x16, 0x75, 0x59, 0xd4, 0x16, 0x28,
	0x96, 0x86, 0x0c, 0xd5, 0xef, 0x4a, 0x0b, 0xdb, 0x24, 0xa2, 0xf8, 0x64, 0x40, 0xfb, 0x43, 0xfc,
	0x72, 0xdf, 0xa6, 0x9c, 0xec, 0xe3, 0x1e, 0xf1, 0xfc, 0x90, 0x70, 0x9f, 0x85, 0x2a, 0xb6, 0xec,
	0x31, 0xe6, 0x05, 0x14, 0x93, 0x9e, 0x8f, 0x49, 0x18, 0x32, 0x2e, 0xc0, 0xa4, 0x92, 0x3e, 0xc7,
	0x46, 0xfc, 0x4a, 0xcc, 0xfc, 0x0a, 0xe0, 0xb5, 0x66, 0xe4, 0x1d, 0x31, 0xaf, 0xee, 0xc4, 0x39,
	0x48, 0x83, 0xab, 0x4e, 0x9f, 0x12, 0xce, 0xfa, 0x1a, 0xd8, 0x01, 0x7b, 0xa5, 0x56, 0x62, 0xa2,
	0x1b, 0xb0, 0xd0, 0x65, 0xee, 0x20, 0xa0, 0x5a, 0x4e, 0x00, 0xca, 0x8a, 0xfd, 0x44, 0xe4, 0x6a,
	0x79, 0xe9, 0x97, 0x16, 0xda, 0x80, 0x2b, 0xc4, 0x89, 0xeb, 0x2c, 0x0b, 0xb7, 0x34, 0xd0, 0x36,
	0x2c, 0x71, 0xd2, 0xf7, 0x28, 0x6f, 0xfb, 0xae, 0xb6, 0x22, 0x90, 0xa2, 0x74, 0x3c, 0x76, 0x63,
	0xd0, 0x25, 0x9c, 0xb4, 0x3b, 0x24, 0xea, 0x68, 0x05, 0x09, 0xc6, 0x8e, 0x47, 0x24, 0xea, 0x20,
	0x1d, 0x16, 0xbb, 0x94, 0x93, 0xd8, 0xd6, 0x56, 0x25, 0x96, 0xd8, 0x66, 0x05, 0x6e, 0x4c, 0x4f,
	0xd1, 0xa2, 0x51, 0x8f, 0x85, 0x11, 0x45, 0xeb, 0x30, 0xe7, 0xbb, 0x62, 0x90, 0xe5, 0x56, 0xce,
	0x77, 0xcd, 0x3b, 0x70, 0xf3, 0x38, 0x5e, 0xe5, 0x21, 0xe5, 0xf5, 0x78, 0x0b, 0x47, 0xcc, 0x6b,
	0xd1, 0x93, 0x01, 0x8d, 0xf8, 0x42, 0xe8, 0x31, 0xd4, 0x16, 0x43, 0x55, 0xd9, 0x87, 0xb0, 0x24,
	0x96, 0xd8, 0x0e, 0x98, 0x27, 0x52, 0xd6, 0x6a, 0x9a, 0x35, 0xfb, 0x6a, 0xad, 0x3f, 0x49, 0x45,
	0xa2, 0x9e, 0x4c, 0xa2, 0xba, 0xd7, 0x83, 0x60, 0xbe, 0x7b, 0x03, 0xc2, 0xc9, 0x5b, 0x55, 0x25,
	0x2b, 0x96, 0x12, 0x44, 0x2c, 0x01, 0x4b, 0x48, 0xc0, 0x52, 0x12, 0xb0, 0x9e, 0x12, 0x8f, 0xaa,
	0xdc, 0xd6, 0x54, 0xa6, 0xf9, 0x11, 0x28, 0xda, 0x33, 0x3d, 0xd2, 0x69, 0xe7, 0xaf, 0x46, 0x1b,
	0x1d, 0xce, 0x70, 0xcb, 0x09, 0x6e, 0xbb, 0x97, 0x72, 0x93, 0x3d, 0x67, 0xc8, 0xbd, 0x86, 0x65,
	0xc9, 0x4d, 0x55, 0x3e, 0x18, 0x36, 0x85, 0x84, 0x92, 0x25, 0x4c, 0x14, 0x06, 0x66, 0x14, 0xd6,
	0x48, 0x21, 0xf0, 0x2f, 0xcb, 0xf9, 0x04, 0xe0, 0xcd, 0x0c, 0x02, 0xff, 0xc7, 0x86, 0x6a, 0xcf,
	0x60, 0xbe, 0x19, 0x79, 0xe8, 0x09, 0x2c, 0x4d, 0x4e, 0x64, 0x79, 0x9e, 0xc0, 0xb4, 0xd2, 0xf5,
	0xdb, 0x7f, 0x43, 0x93, 0x1e, 0xb5, 0x2f, 0x79, 0xb8, 0x22, 0x26, 0x47, 0xef, 0x00, 0x2c, 0x26,
	0x13, 0xa0, 0xdd, 0xf9, 0xe4, 0x8c, 0xc3, 0xa1, 0xef, 0x5d, 0x1e, 0x28, 0x3b, 0x99, 0x95, 0x37,
	0xdf, 0x7f, 0x7d, 0xc8, 0xed, 0x20, 0x03, 0xa7, 0xdd, 0x3a, 0xf1, 0x5e, 0xf1, 0x99, 0xef, 0x9e,
	0xa3, 0xb7, 0x00, 0xae, 0x25, 0xc9, 0xf5, 0x20, 0xc8, 0xa0, 0xb2, 0x78, 0x52, 0x32, 0xa8, 0xa4,
	0xc8, 0xdd, 0xbc, 0x25, 0xa8, 0x6c, 0xa3, 0xad, 0x4c, 0x2a, 0xe8, 0x33, 0x80, 0xd7, 0xe7, 0xc5,
	0x80, 0xaa, 0xe9, 0x1d, 0xd2, 0x45, 0xab, 0xdf, 0xbb, 0x62, 0xb4, 0x22, 0xf5, 0x40, 0x90, 0xb2,
	0x50, 0x35, 0x7b, 0x3f, 0xf6, 0xb0, 0x2d, 0x85, 0x8f, 0xcf, 0xe4, 0xff, 0xf9, 0x41, 0xe3, 0xdb,
	0xc8, 0x00, 0x17, 0x23, 0x03, 0xfc, 0x1c, 0x19, 0xe0, 0xfd, 0xd8, 0x58, 0xba, 0x18, 0x1b, 0x4b,
	0x3f, 0xc6, 0xc6, 0xd2, 0xf3, 0xaa, 0xe7, 0xf3, 0xce, 0xc0, 0xb6, 0x1c, 0xd6, 0x9d, 0x54, 0xb4,
	0x03, 0xe6, 0xbc, 0x90, 0x8f, 0xa7, 0xc9, 0x27, 0x68, 0xd8, 0xa3, 0x91, 0x5d, 0x10, 0xb7, 0xfe,
	0xfd, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0x6e, 0xb5, 0x34, 0xa1, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// LogAction records an audit log entry (internal, may be restricted to agent authority)
	LogAction(ctx context.Context, in *MsgLogAction, opts ...grpc.CallOption) (*MsgLogActionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) LogAction(ctx context.Context, in *MsgLogAction, opts ...grpc.CallOption) (*MsgLogActionResponse, error) {
	out := new(MsgLogActionResponse)
	err := c.cc.Invoke(ctx, "/bizchain.audit.Msg/LogAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// LogAction records an audit log entry (internal, may be restricted to agent authority)
	LogAction(context.Context, *MsgLogAction) (*MsgLogActionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) LogAction(ctx context.Context, req *MsgLogAction) (*MsgLogActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogAction not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_LogAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLogAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LogAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bizchain.audit.Msg/LogAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LogAction(ctx, req.(*MsgLogAction))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bizchain.audit.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogAction",
			Handler:    _Msg_LogAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bizchain/audit/tx.proto",
}

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// AuditLog queries an audit log by ID
	AuditLog(ctx context.Context, in *QueryGetAuditLogRequest, opts ...grpc.CallOption) (*QueryGetAuditLogResponse, error)
	// AuditLogAll queries all audit logs (paginated)
	AuditLogAll(ctx context.Context, in *QueryAllAuditLogRequest, opts ...grpc.CallOption) (*QueryAllAuditLogResponse, error)
	// AuditLogByModule queries audit logs filtered by module
	AuditLogByModule(ctx context.Context, in *QueryAuditLogByModuleRequest, opts ...grpc.CallOption) (*QueryAuditLogByModuleResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) AuditLog(ctx context.Context, in *QueryGetAuditLogRequest, opts ...grpc.CallOption) (*QueryGetAuditLogResponse, error) {
	out := new(QueryGetAuditLogResponse)
	err := c.cc.Invoke(ctx, "/bizchain.audit.Query/AuditLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuditLogAll(ctx context.Context, in *QueryAllAuditLogRequest, opts ...grpc.CallOption) (*QueryAllAuditLogResponse, error) {
	out := new(QueryAllAuditLogResponse)
	err := c.cc.Invoke(ctx, "/bizchain.audit.Query/AuditLogAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuditLogByModule(ctx context.Context, in *QueryAuditLogByModuleRequest, opts ...grpc.CallOption) (*QueryAuditLogByModuleResponse, error) {
	out := new(QueryAuditLogByModuleResponse)
	err := c.cc.Invoke(ctx, "/bizchain.audit.Query/AuditLogByModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// AuditLog queries an audit log by ID
	AuditLog(context.Context, *QueryGetAuditLogRequest) (*QueryGetAuditLogResponse, error)
	// AuditLogAll queries all audit logs (paginated)
	AuditLogAll(context.Context, *QueryAllAuditLogRequest) (*QueryAllAuditLogResponse, error)
	// AuditLogByModule queries audit logs filtered by module
	AuditLogByModule(context.Context, *QueryAuditLogByModuleRequest) (*QueryAuditLogByModuleResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) AuditLog(ctx context.Context, req *QueryGetAuditLogRequest) (*QueryGetAuditLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditLog not implemented")
}
func (*UnimplementedQueryServer) AuditLogAll(ctx context.Context, req *QueryAllAuditLogRequest) (*QueryAllAuditLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditLogAll not implemented")
}
func (*UnimplementedQueryServer) AuditLogByModule(ctx context.Context, req *QueryAuditLogByModuleRequest) (*QueryAuditLogByModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditLogByModule not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_AuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bizchain.audit.Query/AuditLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditLog(ctx, req.(*QueryGetAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuditLogAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditLogAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bizchain.audit.Query/AuditLogAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditLogAll(ctx, req.(*QueryAllAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuditLogByModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditLogByModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditLogByModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bizchain.audit.Query/AuditLogByModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditLogByModule(ctx, req.(*QueryAuditLogByModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bizchain.audit.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuditLog",
			Handler:    _Query_AuditLog_Handler,
		},
		{
			MethodName: "AuditLogAll",
			Handler:    _Query_AuditLogAll_Handler,
		},
		{
			MethodName: "AuditLogByModule",
			Handler:    _Query_AuditLogByModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bizchain/audit/tx.proto",
}

func (m *MsgLogAction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLogAction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLogAction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.DataHash) > 0 {
		i -= len(m.DataHash)
		copy(dAtA[i:], m.DataHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DataHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TargetId) > 0 {
		i -= len(m.TargetId)
		copy(dAtA[i:], m.TargetId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Actor) > 0 {
		i -= len(m.Actor)
		copy(dAtA[i:], m.Actor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Actor)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Action) > 0 {
		i -= len(m.Action)
		copy(dAtA[i:], m.Action)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Action)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLogActionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLogActionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLogActionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuditLogRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuditLogRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuditLogRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuditLogResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuditLogResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuditLogResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AuditLog != nil {
		{
			size, err := m.AuditLog.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAuditLogRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuditLogRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuditLogRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAuditLogResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuditLogResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuditLogResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuditLog) > 0 {
		for iNdEx := len(m.AuditLog) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuditLog[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuditLogByModuleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditLogByModuleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditLogByModuleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuditLogByModuleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditLogByModuleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditLogByModuleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuditLog) > 0 {
		for iNdEx := len(m.AuditLog) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuditLog[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLogAction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Action)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Actor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DataHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgLogActionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *QueryGetAuditLogRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *QueryGetAuditLogResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuditLog != nil {
		l = m.AuditLog.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *QueryAllAuditLogRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *QueryAllAuditLogResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuditLog) > 0 {
		for _, e := range m.AuditLog {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *QueryAuditLogByModuleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *QueryAuditLogByModuleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuditLog) > 0 {
		for _, e := range m.AuditLog {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLogAction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLogAction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLogAction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Action = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLogActionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLogActionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLogActionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuditLogRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuditLogRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuditLogRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuditLogResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuditLogResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuditLogResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditLog", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AuditLog == nil {
				m.AuditLog = &AuditLog{}
			}
			if err := m.AuditLog.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuditLogRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuditLogRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuditLogRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuditLogResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuditLogResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuditLogResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditLog", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditLog = append(m.AuditLog, &AuditLog{})
			if err := m.AuditLog[len(m.AuditLog)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditLogByModuleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditLogByModuleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditLogByModuleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditLogByModuleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditLogByModuleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditLogByModuleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditLog", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditLog = append(m.AuditLog, &AuditLog{})
			if err := m.AuditLog[len(m.AuditLog)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
