// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bizchain/keberangkatan/keberangkatan.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BaggageItem represents a checked baggage item tracked via QR/NFC
type BaggageItem struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag       string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Weight    string `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *BaggageItem) Reset()         { *m = BaggageItem{} }
func (m *BaggageItem) String() string { return proto.CompactTextString(m) }
func (*BaggageItem) ProtoMessage()    {}
func (*BaggageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d6436ff07d5812, []int{0}
}
func (m *BaggageItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaggageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaggageItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaggageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaggageItem.Merge(m, src)
}
func (m *BaggageItem) XXX_Size() int {
	return m.Size()
}
func (m *BaggageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BaggageItem.DiscardUnknown(m)
}

var xxx_messageInfo_BaggageItem proto.InternalMessageInfo

func (m *BaggageItem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BaggageItem) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *BaggageItem) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *BaggageItem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BaggageItem) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Keberangkatan tracks a pilgrim's departure journey through 9 stages
// Status: 1. Daftar 2. DP Dibayar 3. Visa Diproses 4. Visa Terbit 5. Tiket Terbit
//  6. Hotel Confirm 7. Manasik 8. Berangkat 9. Pulang
type Keberangkatan struct {
	Id             uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Jamaah         string         `protobuf:"bytes,2,opt,name=jamaah,proto3" json:"jamaah,omitempty"`
	PaketId        uint64         `protobuf:"varint,3,opt,name=paket_id,json=paketId,proto3" json:"paket_id,omitempty"`
	PembayaranId   uint64         `protobuf:"varint,4,opt,name=pembayaran_id,json=pembayaranId,proto3" json:"pembayaran_id,omitempty"`
	Stage          uint64         `protobuf:"varint,5,opt,name=stage,proto3" json:"stage,omitempty"`
	StatusLabel    string         `protobuf:"bytes,6,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`
	DepartureDate  string         `protobuf:"bytes,7,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	ReturnDate     string         `protobuf:"bytes,8,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	ManasikDate    string         `protobuf:"bytes,9,opt,name=manasik_date,json=manasikDate,proto3" json:"manasik_date,omitempty"`
	HotelConfirm   string         `protobuf:"bytes,10,opt,name=hotel_confirm,json=hotelConfirm,proto3" json:"hotel_confirm,omitempty"`
	AirlineConfirm string         `protobuf:"bytes,11,opt,name=airline_confirm,json=airlineConfirm,proto3" json:"airline_confirm,omitempty"`
	Baggage        []*BaggageItem `protobuf:"bytes,12,rep,name=baggage,proto3" json:"baggage,omitempty"`
	Creator        string         `protobuf:"bytes,13,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt      string         `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string         `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Keberangkatan) Reset()         { *m = Keberangkatan{} }
func (m *Keberangkatan) String() string { return proto.CompactTextString(m) }
func (*Keberangkatan) ProtoMessage()    {}
func (*Keberangkatan) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d6436ff07d5812, []int{1}
}
func (m *Keberangkatan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Keberangkatan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Keberangkatan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Keberangkatan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keberangkatan.Merge(m, src)
}
func (m *Keberangkatan) XXX_Size() int {
	return m.Size()
}
func (m *Keberangkatan) XXX_DiscardUnknown() {
	xxx_messageInfo_Keberangkatan.DiscardUnknown(m)
}

var xxx_messageInfo_Keberangkatan proto.InternalMessageInfo

func (m *Keberangkatan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Keberangkatan) GetJamaah() string {
	if m != nil {
		return m.Jamaah
	}
	return ""
}

func (m *Keberangkatan) GetPaketId() uint64 {
	if m != nil {
		return m.PaketId
	}
	return 0
}

func (m *Keberangkatan) GetPembayaranId() uint64 {
	if m != nil {
		return m.PembayaranId
	}
	return 0
}

func (m *Keberangkatan) GetStage() uint64 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *Keberangkatan) GetStatusLabel() string {
	if m != nil {
		return m.StatusLabel
	}
	return ""
}

func (m *Keberangkatan) GetDepartureDate() string {
	if m != nil {
		return m.DepartureDate
	}
	return ""
}

func (m *Keberangkatan) GetReturnDate() string {
	if m != nil {
		return m.ReturnDate
	}
	return ""
}

func (m *Keberangkatan) GetManasikDate() string {
	if m != nil {
		return m.ManasikDate
	}
	return ""
}

func (m *Keberangkatan) GetHotelConfirm() string {
	if m != nil {
		return m.HotelConfirm
	}
	return ""
}

func (m *Keberangkatan) GetAirlineConfirm() string {
	if m != nil {
		return m.AirlineConfirm
	}
	return ""
}

func (m *Keberangkatan) GetBaggage() []*BaggageItem {
	if m != nil {
		return m.Baggage
	}
	return nil
}

func (m *Keberangkatan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Keberangkatan) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Keberangkatan) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Params defines the parameters for the keberangkatan module
type Params struct {
	ZeroFeeEnabled bool `protobuf:"varint,1,opt,name=zero_fee_enabled,json=zeroFeeEnabled,proto3" json:"zero_fee_enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d6436ff07d5812, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetZeroFeeEnabled() bool {
	if m != nil {
		return m.ZeroFeeEnabled
	}
	return false
}

// GenesisState defines the genesis state of the keberangkatan module
type GenesisState struct {
	KeberangkatanList  []*Keberangkatan `protobuf:"bytes,1,rep,name=keberangkatan_list,json=keberangkatanList,proto3" json:"keberangkatan_list,omitempty"`
	KeberangkatanCount uint64           `protobuf:"varint,2,opt,name=keberangkatan_count,json=keberangkatanCount,proto3" json:"keberangkatan_count,omitempty"`
	BaggageCount       uint64           `protobuf:"varint,3,opt,name=baggage_count,json=baggageCount,proto3" json:"baggage_count,omitempty"`
	Params             *Params          `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d6436ff07d5812, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetKeberangkatanList() []*Keberangkatan {
	if m != nil {
		return m.KeberangkatanList
	}
	return nil
}

func (m *GenesisState) GetKeberangkatanCount() uint64 {
	if m != nil {
		return m.KeberangkatanCount
	}
	return 0
}

func (m *GenesisState) GetBaggageCount() uint64 {
	if m != nil {
		return m.BaggageCount
	}
	return 0
}

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*BaggageItem)(nil), "bizchain.keberangkatan.BaggageItem")
	proto.RegisterType((*Keberangkatan)(nil), "bizchain.keberangkatan.Keberangkatan")
	proto.RegisterType((*Params)(nil), "bizchain.keberangkatan.Params")
	proto.RegisterType((*GenesisState)(nil), "bizchain.keberangkatan.GenesisState")
}

func init() {
	proto.RegisterFile("bizchain/keberangkatan/keberangkatan.proto", fileDescriptor_30d6436ff07d5812)
}

var fileDescriptor_30d6436ff07d5812 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xeb, 0xd6, 0x4d, 0xda, 0x89, 0x93, 0x96, 0x05, 0x55, 0xcb, 0x01, 0xd3, 0x0f, 0x55,
	0x44, 0x1c, 0x52, 0xa9, 0x20, 0x6e, 0x1c, 0xda, 0xf2, 0xa1, 0x8a, 0x0a, 0x21, 0xc3, 0x89, 0x8b,
	0x35, 0x8e, 0xa7, 0xce, 0x12, 0x7f, 0x69, 0x3d, 0x11, 0xb4, 0x07, 0xc4, 0x23, 0xf0, 0x58, 0x1c,
	0x7b, 0xe4, 0x88, 0xda, 0x37, 0xe0, 0x09, 0x90, 0x77, 0x9d, 0xd2, 0x04, 0x7a, 0xdb, 0xf9, 0xcd,
	0xdf, 0xde, 0x99, 0x9d, 0xbf, 0x06, 0x1e, 0x47, 0xea, 0x7c, 0x38, 0x42, 0x95, 0xef, 0x8d, 0x29,
	0x22, 0x8d, 0x79, 0x32, 0x46, 0xc6, 0xb9, 0x68, 0x50, 0xea, 0x82, 0x0b, 0xb1, 0x31, 0xd5, 0x0e,
	0x66, 0xb2, 0xdb, 0x5f, 0xa1, 0x73, 0x88, 0x49, 0x82, 0x09, 0x1d, 0x33, 0x65, 0xa2, 0x07, 0x8b,
	0x2a, 0x96, 0xce, 0xa6, 0xd3, 0x77, 0x83, 0x45, 0x15, 0x8b, 0x75, 0x58, 0x62, 0x4c, 0xe4, 0xe2,
	0xa6, 0xd3, 0x5f, 0x0d, 0xea, 0xa3, 0xd8, 0x80, 0xd6, 0x67, 0x52, 0xc9, 0x88, 0xe5, 0x92, 0x81,
	0x4d, 0x54, 0xf3, 0x8a, 0x91, 0x27, 0x95, 0x74, 0x2d, 0xb7, 0x91, 0x78, 0x00, 0x30, 0x29, 0x63,
	0x64, 0x8a, 0x43, 0x64, 0xb9, 0x6c, 0x72, 0xab, 0x0d, 0x39, 0xe0, 0xed, 0x6f, 0x2e, 0x74, 0xdf,
	0xdc, 0xac, 0xe8, 0x9f, 0x12, 0x36, 0xa0, 0xf5, 0x09, 0x33, 0xc4, 0x51, 0x53, 0x45, 0x13, 0x89,
	0xfb, 0xb0, 0x52, 0xe2, 0x98, 0x38, 0x54, 0xb1, 0x29, 0xc5, 0x0d, 0xda, 0x26, 0x3e, 0x8e, 0xc5,
	0x0e, 0x74, 0x4b, 0xca, 0x22, 0x3c, 0x43, 0x8d, 0x79, 0x9d, 0x77, 0x4d, 0xde, 0xfb, 0x0b, 0x8f,
	0x63, 0x71, 0x0f, 0x96, 0x2b, 0xc6, 0x84, 0x4c, 0x4d, 0x6e, 0x60, 0x03, 0xb1, 0x05, 0x9e, 0x2d,
	0x3c, 0x4c, 0x31, 0xa2, 0x54, 0xb6, 0xcc, 0x9d, 0x1d, 0xcb, 0x4e, 0x6a, 0x24, 0x76, 0xa1, 0x17,
	0x53, 0x89, 0x9a, 0x27, 0x9a, 0xc2, 0xba, 0x0f, 0xd9, 0x36, 0xa2, 0xee, 0x35, 0x7d, 0x81, 0x4c,
	0xe2, 0x21, 0x74, 0x34, 0xf1, 0x44, 0xe7, 0x56, 0xb3, 0x62, 0x34, 0x60, 0x91, 0x11, 0x6c, 0x81,
	0x97, 0x61, 0x8e, 0x95, 0x1a, 0x5b, 0xc5, 0xaa, 0xbd, 0xaa, 0x61, 0x46, 0xb2, 0x03, 0xdd, 0x51,
	0xc1, 0x94, 0x86, 0xc3, 0x22, 0x3f, 0x55, 0x3a, 0x93, 0x60, 0x34, 0x9e, 0x81, 0x47, 0x96, 0x89,
	0x47, 0xb0, 0x86, 0x4a, 0xa7, 0x2a, 0xa7, 0x6b, 0x59, 0xc7, 0xc8, 0x7a, 0x0d, 0x9e, 0x0a, 0x9f,
	0x43, 0x3b, 0xb2, 0xb3, 0x96, 0xde, 0xe6, 0x52, 0xbf, 0xb3, 0xbf, 0x33, 0xf8, 0xbf, 0x2b, 0x06,
	0x37, 0x2c, 0x11, 0x4c, 0xbf, 0x11, 0x12, 0xda, 0x43, 0x4d, 0xc8, 0x85, 0x96, 0x5d, 0xf3, 0xff,
	0x69, 0x58, 0xcf, 0xd8, 0x1c, 0xed, 0x8c, 0x7b, 0x76, 0xc6, 0x0d, 0x39, 0xe0, 0x39, 0x0b, 0xac,
	0xcd, 0x5b, 0x60, 0x1f, 0x5a, 0xef, 0x50, 0x63, 0x56, 0x89, 0x3e, 0xac, 0x9f, 0x93, 0x2e, 0xc2,
	0x53, 0xa2, 0x90, 0x72, 0x8c, 0x52, 0xb2, 0x46, 0x58, 0x09, 0x7a, 0x35, 0x7f, 0x45, 0xf4, 0xd2,
	0xd2, 0xed, 0xdf, 0x0e, 0x78, 0xaf, 0x29, 0xa7, 0x4a, 0x55, 0xef, 0xb9, 0x7e, 0xa9, 0x0f, 0x20,
	0x66, 0x5a, 0x08, 0x53, 0x55, 0xb1, 0x74, 0x4c, 0x9b, 0xbb, 0xb7, 0xb5, 0x39, 0x63, 0xbc, 0xe0,
	0xce, 0x4c, 0xf2, 0x44, 0x55, 0x2c, 0xf6, 0xe0, 0xee, 0xec, 0x5f, 0x87, 0xc5, 0x24, 0x67, 0x63,
	0x44, 0x37, 0x98, 0xbd, 0xf0, 0xa8, 0xce, 0xd4, 0x03, 0x6b, 0x9e, 0xab, 0x91, 0x5a, 0x67, 0x7a,
	0x0d, 0xb4, 0xa2, 0x67, 0xd0, 0x2a, 0x4d, 0xc3, 0xc6, 0x97, 0x9d, 0x7d, 0xff, 0xb6, 0xfa, 0xec,
	0xb3, 0x04, 0x8d, 0xfa, 0xf0, 0xed, 0x8f, 0x4b, 0xdf, 0xb9, 0xb8, 0xf4, 0x9d, 0x5f, 0x97, 0xbe,
	0xf3, 0xfd, 0xca, 0x5f, 0xb8, 0xb8, 0xf2, 0x17, 0x7e, 0x5e, 0xf9, 0x0b, 0x1f, 0x9f, 0x26, 0x8a,
	0x47, 0x93, 0x68, 0x30, 0x2c, 0xb2, 0xbd, 0xeb, 0xa5, 0x10, 0xa5, 0xc5, 0x70, 0x6c, 0x8f, 0x5f,
	0xe6, 0x36, 0x04, 0x9f, 0x95, 0x54, 0x45, 0x2d, 0xb3, 0x1a, 0x9e, 0xfc, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xd9, 0xf0, 0x74, 0x6e, 0x48, 0x04, 0x00, 0x00,
}

func (m *BaggageItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaggageItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaggageItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Weight) > 0 {
		i -= len(m.Weight)
		copy(dAtA[i:], m.Weight)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.Weight)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tag) > 0 {
		i -= len(m.Tag)
		copy(dAtA[i:], m.Tag)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.Tag)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintKeberangkatan(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Keberangkatan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Keberangkatan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Keberangkatan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Baggage) > 0 {
		for iNdEx := len(m.Baggage) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Baggage[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintKeberangkatan(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.AirlineConfirm) > 0 {
		i -= len(m.AirlineConfirm)
		copy(dAtA[i:], m.AirlineConfirm)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.AirlineConfirm)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.HotelConfirm) > 0 {
		i -= len(m.HotelConfirm)
		copy(dAtA[i:], m.HotelConfirm)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.HotelConfirm)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.ManasikDate) > 0 {
		i -= len(m.ManasikDate)
		copy(dAtA[i:], m.ManasikDate)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.ManasikDate)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ReturnDate) > 0 {
		i -= len(m.ReturnDate)
		copy(dAtA[i:], m.ReturnDate)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.ReturnDate)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DepartureDate) > 0 {
		i -= len(m.DepartureDate)
		copy(dAtA[i:], m.DepartureDate)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.DepartureDate)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.StatusLabel) > 0 {
		i -= len(m.StatusLabel)
		copy(dAtA[i:], m.StatusLabel)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.StatusLabel)))
		i--
		dAtA[i] = 0x32
	}
	if m.Stage != 0 {
		i = encodeVarintKeberangkatan(dAtA, i, uint64(m.Stage))
		i--
		dAtA[i] = 0x28
	}
	if m.PembayaranId != 0 {
		i = encodeVarintKeberangkatan(dAtA, i, uint64(m.PembayaranId))
		i--
		dAtA[i] = 0x20
	}
	if m.PaketId != 0 {
		i = encodeVarintKeberangkatan(dAtA, i, uint64(m.PaketId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Jamaah) > 0 {
		i -= len(m.Jamaah)
		copy(dAtA[i:], m.Jamaah)
		i = encodeVarintKeberangkatan(dAtA, i, uint64(len(m.Jamaah)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintKeberangkatan(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		i--
		if m.ZeroFeeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintKeberangkatan(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.BaggageCount != 0 {
		i = encodeVarintKeberangkatan(dAtA, i, uint64(m.BaggageCount))
		i--
		dAtA[i] = 0x18
	}
	if m.KeberangkatanCount != 0 {
		i = encodeVarintKeberangkatan(dAtA, i, uint64(m.KeberangkatanCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.KeberangkatanList) > 0 {
		for iNdEx := len(m.KeberangkatanList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeberangkatanList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintKeberangkatan(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintKeberangkatan(dAtA []byte, offset int, v uint64) int {
	offset -= sovKeberangkatan(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BaggageItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovKeberangkatan(uint64(m.Id))
	}
	l = len(m.Tag)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.Weight)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	return n
}

func (m *Keberangkatan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovKeberangkatan(uint64(m.Id))
	}
	l = len(m.Jamaah)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	if m.PaketId != 0 {
		n += 1 + sovKeberangkatan(uint64(m.PaketId))
	}
	if m.PembayaranId != 0 {
		n += 1 + sovKeberangkatan(uint64(m.PembayaranId))
	}
	if m.Stage != 0 {
		n += 1 + sovKeberangkatan(uint64(m.Stage))
	}
	l = len(m.StatusLabel)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.DepartureDate)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.ReturnDate)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.ManasikDate)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.HotelConfirm)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.AirlineConfirm)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	if len(m.Baggage) > 0 {
		for _, e := range m.Baggage {
			l = e.Size()
			n += 1 + l + sovKeberangkatan(uint64(l))
		}
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		n += 2
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.KeberangkatanList) > 0 {
		for _, e := range m.KeberangkatanList {
			l = e.Size()
			n += 1 + l + sovKeberangkatan(uint64(l))
		}
	}
	if m.KeberangkatanCount != 0 {
		n += 1 + sovKeberangkatan(uint64(m.KeberangkatanCount))
	}
	if m.BaggageCount != 0 {
		n += 1 + sovKeberangkatan(uint64(m.BaggageCount))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovKeberangkatan(uint64(l))
	}
	return n
}

func sovKeberangkatan(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKeberangkatan(x uint64) (n int) {
	return sovKeberangkatan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BaggageItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeberangkatan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaggageItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaggageItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeberangkatan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Keberangkatan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeberangkatan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Keberangkatan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Keberangkatan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jamaah", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Jamaah = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaketId", wireType)
			}
			m.PaketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PembayaranId", wireType)
			}
			m.PembayaranId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PembayaranId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stage", wireType)
			}
			m.Stage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusLabel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusLabel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepartureDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepartureDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReturnDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReturnDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ManasikDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ManasikDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HotelConfirm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HotelConfirm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirlineConfirm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AirlineConfirm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Baggage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Baggage = append(m.Baggage, &BaggageItem{})
			if err := m.Baggage[len(m.Baggage)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeberangkatan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeberangkatan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZeroFeeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ZeroFeeEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipKeberangkatan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeberangkatan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeberangkatanList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeberangkatanList = append(m.KeberangkatanList, &Keberangkatan{})
			if err := m.KeberangkatanList[len(m.KeberangkatanList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeberangkatanCount", wireType)
			}
			m.KeberangkatanCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeberangkatanCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaggageCount", wireType)
			}
			m.BaggageCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaggageCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeberangkatan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeberangkatan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKeberangkatan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKeberangkatan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeberangkatan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKeberangkatan
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKeberangkatan
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKeberangkatan
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKeberangkatan        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKeberangkatan          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKeberangkatan = fmt.Errorf("proto: unexpected end of group")
)
