// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bizchain/oleholeh/oleholeh.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OlehOlehProduct represents a souvenir product in the oleh-oleh marketplace
type OlehOlehProduct struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl    string `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Stock       uint64 `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Seller      string `protobuf:"bytes,7,opt,name=seller,proto3" json:"seller,omitempty"`
	Category    string `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Status      string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Creator     string `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt   string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *OlehOlehProduct) Reset()         { *m = OlehOlehProduct{} }
func (m *OlehOlehProduct) String() string { return proto.CompactTextString(m) }
func (*OlehOlehProduct) ProtoMessage()    {}
func (*OlehOlehProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ee27c3a5c8aef4, []int{0}
}
func (m *OlehOlehProduct) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OlehOlehProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OlehOlehProduct.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OlehOlehProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OlehOlehProduct.Merge(m, src)
}
func (m *OlehOlehProduct) XXX_Size() int {
	return m.Size()
}
func (m *OlehOlehProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_OlehOlehProduct.DiscardUnknown(m)
}

var xxx_messageInfo_OlehOlehProduct proto.InternalMessageInfo

func (m *OlehOlehProduct) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OlehOlehProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OlehOlehProduct) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OlehOlehProduct) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OlehOlehProduct) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *OlehOlehProduct) GetStock() uint64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *OlehOlehProduct) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *OlehOlehProduct) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *OlehOlehProduct) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OlehOlehProduct) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *OlehOlehProduct) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OlehOlehProduct) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// OlehOlehOrder represents a pre-order of oleh-oleh paid via wallet
type OlehOlehOrder struct {
	Id              uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId       uint64 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName     string `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Jamaah          string `protobuf:"bytes,4,opt,name=jamaah,proto3" json:"jamaah,omitempty"`
	Quantity        uint64 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Total           string `protobuf:"bytes,6,opt,name=total,proto3" json:"total,omitempty"`
	Status          string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ShippingAddress string `protobuf:"bytes,8,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Creator         string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt       string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *OlehOlehOrder) Reset()         { *m = OlehOlehOrder{} }
func (m *OlehOlehOrder) String() string { return proto.CompactTextString(m) }
func (*OlehOlehOrder) ProtoMessage()    {}
func (*OlehOlehOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ee27c3a5c8aef4, []int{1}
}
func (m *OlehOlehOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OlehOlehOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OlehOlehOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OlehOlehOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OlehOlehOrder.Merge(m, src)
}
func (m *OlehOlehOrder) XXX_Size() int {
	return m.Size()
}
func (m *OlehOlehOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_OlehOlehOrder.DiscardUnknown(m)
}

var xxx_messageInfo_OlehOlehOrder proto.InternalMessageInfo

func (m *OlehOlehOrder) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OlehOlehOrder) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OlehOlehOrder) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *OlehOlehOrder) GetJamaah() string {
	if m != nil {
		return m.Jamaah
	}
	return ""
}

func (m *OlehOlehOrder) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OlehOlehOrder) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *OlehOlehOrder) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OlehOlehOrder) GetShippingAddress() string {
	if m != nil {
		return m.ShippingAddress
	}
	return ""
}

func (m *OlehOlehOrder) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *OlehOlehOrder) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OlehOlehOrder) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Params defines the parameters for the oleholeh module
type Params struct {
	ZeroFeeEnabled bool `protobuf:"varint,1,opt,name=zero_fee_enabled,json=zeroFeeEnabled,proto3" json:"zero_fee_enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ee27c3a5c8aef4, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetZeroFeeEnabled() bool {
	if m != nil {
		return m.ZeroFeeEnabled
	}
	return false
}

// GenesisState defines the genesis state of the oleholeh module
type GenesisState struct {
	ProductList  []*OlehOlehProduct `protobuf:"bytes,1,rep,name=product_list,json=productList,proto3" json:"product_list,omitempty"`
	OrderList    []*OlehOlehOrder   `protobuf:"bytes,2,rep,name=order_list,json=orderList,proto3" json:"order_list,omitempty"`
	ProductCount uint64             `protobuf:"varint,3,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	OrderCount   uint64             `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Params       *Params            `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ee27c3a5c8aef4, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetProductList() []*OlehOlehProduct {
	if m != nil {
		return m.ProductList
	}
	return nil
}

func (m *GenesisState) GetOrderList() []*OlehOlehOrder {
	if m != nil {
		return m.OrderList
	}
	return nil
}

func (m *GenesisState) GetProductCount() uint64 {
	if m != nil {
		return m.ProductCount
	}
	return 0
}

func (m *GenesisState) GetOrderCount() uint64 {
	if m != nil {
		return m.OrderCount
	}
	return 0
}

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*OlehOlehProduct)(nil), "bizchain.oleholeh.OlehOlehProduct")
	proto.RegisterType((*OlehOlehOrder)(nil), "bizchain.oleholeh.OlehOlehOrder")
	proto.RegisterType((*Params)(nil), "bizchain.oleholeh.Params")
	proto.RegisterType((*GenesisState)(nil), "bizchain.oleholeh.GenesisState")
}

func init() { proto.RegisterFile("bizchain/oleholeh/oleholeh.proto", fileDescriptor_70ee27c3a5c8aef4) }

var fileDescriptor_70ee27c3a5c8aef4 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0x6b, 0xd7, 0x4d, 0xe3, 0x9b, 0xfe, 0xfb, 0x46, 0x9f, 0xaa, 0x69, 0x51, 0x43, 0x08,
	0x9b, 0xb0, 0x49, 0x44, 0x79, 0x00, 0x54, 0x50, 0x41, 0x95, 0x10, 0xad, 0x8c, 0xd8, 0xb0, 0xb1,
	0x26, 0xf6, 0x25, 0x19, 0x6a, 0x7b, 0xcc, 0xcc, 0x58, 0xa2, 0x7d, 0x09, 0x78, 0x28, 0x84, 0x58,
	0x76, 0xc9, 0x12, 0xb5, 0x2f, 0x82, 0x7c, 0xc7, 0x4e, 0x4b, 0x8b, 0xba, 0xb0, 0x34, 0xe7, 0x9c,
	0x3b, 0x77, 0x46, 0xbf, 0x9b, 0x0c, 0x0c, 0xa6, 0xf2, 0x3c, 0x99, 0x0b, 0x59, 0x4c, 0x54, 0x86,
	0xf3, 0xfa, 0x5b, 0x2c, 0xc6, 0xa5, 0x56, 0x56, 0xb1, 0xff, 0xda, 0x8a, 0x71, 0x1b, 0xec, 0xee,
	0x24, 0xca, 0xe4, 0xca, 0xc4, 0x54, 0x30, 0x71, 0xc2, 0x55, 0x0f, 0xbf, 0xfb, 0xb0, 0x79, 0x9c,
	0xe1, 0xbc, 0xfe, 0x4e, 0xb4, 0x4a, 0xab, 0xc4, 0xb2, 0x0d, 0xf0, 0x65, 0xca, 0xbd, 0x81, 0x37,
	0x0a, 0x22, 0x5f, 0xa6, 0x8c, 0x41, 0x50, 0x88, 0x1c, 0xb9, 0x3f, 0xf0, 0x46, 0x61, 0x44, 0x6b,
	0x36, 0x80, 0x5e, 0x8a, 0x26, 0xd1, 0xb2, 0xb4, 0x52, 0x15, 0x7c, 0x99, 0xa2, 0x9b, 0x16, 0xfb,
	0x1f, 0x56, 0x4a, 0x2d, 0x13, 0xe4, 0x01, 0x65, 0x4e, 0xb0, 0x07, 0x10, 0xca, 0x5c, 0xcc, 0x30,
	0xae, 0x74, 0xc6, 0x57, 0x28, 0xe9, 0x92, 0xf1, 0x5e, 0x67, 0xf5, 0x16, 0x63, 0x55, 0x72, 0xca,
	0x3b, 0x74, 0xb6, 0x13, 0x6c, 0x1b, 0x3a, 0x06, 0xb3, 0x0c, 0x35, 0x5f, 0xa5, 0xfa, 0x46, 0xb1,
	0x5d, 0xe8, 0x26, 0xc2, 0xe2, 0x4c, 0xe9, 0x33, 0xde, 0x75, 0x9d, 0x5a, 0x4d, 0x7b, 0xac, 0xb0,
	0x95, 0xe1, 0x61, 0xb3, 0x87, 0x14, 0xe3, 0xb0, 0x9a, 0x68, 0x14, 0x56, 0x69, 0x0e, 0x14, 0xb4,
	0x92, 0xed, 0x01, 0xd0, 0x12, 0xd3, 0x58, 0x58, 0xde, 0xa3, 0x30, 0x6c, 0x9c, 0x03, 0x5b, 0xc7,
	0x55, 0x99, 0xb6, 0xf1, 0x9a, 0x8b, 0x1b, 0xe7, 0xc0, 0x0e, 0x7f, 0xf8, 0xb0, 0xde, 0x62, 0x3c,
	0xd6, 0x29, 0xea, 0x3b, 0x10, 0xf7, 0x00, 0x4a, 0xc7, 0x37, 0x96, 0x29, 0xa1, 0x0c, 0xa2, 0xb0,
	0x71, 0x8e, 0x52, 0xf6, 0x08, 0xd6, 0xda, 0x98, 0x58, 0x37, 0x40, 0x1b, 0xef, 0x6d, 0x8d, 0x7c,
	0x1b, 0x3a, 0x9f, 0x44, 0x2e, 0xc4, 0xbc, 0x21, 0xda, 0xa8, 0x9a, 0xc3, 0xe7, 0x4a, 0x14, 0x56,
	0xda, 0x33, 0x22, 0x1a, 0x44, 0x0b, 0x5d, 0x13, 0xb5, 0xca, 0x8a, 0x8c, 0x88, 0x86, 0x91, 0x13,
	0x37, 0xe8, 0xac, 0xfe, 0x45, 0xe7, 0x09, 0x6c, 0x99, 0xb9, 0x2c, 0x4b, 0x59, 0xcc, 0x62, 0x91,
	0xa6, 0x1a, 0x8d, 0x69, 0xc8, 0x6e, 0xb6, 0xfe, 0x81, 0xb3, 0x6f, 0x82, 0x0c, 0xef, 0x03, 0x09,
	0xf7, 0x83, 0xec, 0xdd, 0x06, 0xb9, 0x0f, 0x9d, 0x13, 0xa1, 0x45, 0x6e, 0xd8, 0x08, 0xb6, 0xce,
	0x51, 0xab, 0xf8, 0x23, 0x62, 0x8c, 0x85, 0x98, 0x66, 0xe8, 0x70, 0x76, 0xa3, 0x8d, 0xda, 0x7f,
	0x85, 0x78, 0xe8, 0xdc, 0xe1, 0x57, 0x1f, 0xd6, 0x5e, 0x63, 0x81, 0x46, 0x9a, 0x77, 0x56, 0x58,
	0x64, 0x87, 0xd7, 0x30, 0x33, 0x69, 0x2c, 0xf7, 0x06, 0xcb, 0xa3, 0xde, 0xfe, 0x70, 0x7c, 0xe7,
	0x9f, 0x31, 0xbe, 0xf5, 0xd3, 0x5f, 0x00, 0x7f, 0x23, 0x8d, 0x65, 0xcf, 0x01, 0x54, 0x3d, 0x4b,
	0xd7, 0xc4, 0xa7, 0x26, 0x83, 0x7b, 0x9a, 0xd0, 0xe0, 0xa3, 0x90, 0xf6, 0x50, 0x83, 0xc7, 0xb0,
	0xde, 0xde, 0x23, 0x51, 0x55, 0x61, 0x69, 0xaa, 0x41, 0xd4, 0x5e, 0xee, 0x65, 0xed, 0xb1, 0x87,
	0xd0, 0x73, 0xa7, 0xb8, 0x92, 0x80, 0x4a, 0xdc, 0xc1, 0xae, 0xe0, 0x29, 0x74, 0x4a, 0x42, 0x42,
	0xd3, 0xed, 0xed, 0xef, 0xfc, 0xe3, 0x0a, 0x8e, 0x59, 0xd4, 0x14, 0xbe, 0x38, 0xfa, 0x79, 0xd9,
	0xf7, 0x2e, 0x2e, 0xfb, 0xde, 0xef, 0xcb, 0xbe, 0xf7, 0xed, 0xaa, 0xbf, 0x74, 0x71, 0xd5, 0x5f,
	0xfa, 0x75, 0xd5, 0x5f, 0xfa, 0x30, 0x99, 0x49, 0x3b, 0xaf, 0xa6, 0xe3, 0x44, 0xe5, 0x93, 0xc5,
	0x53, 0x32, 0xcd, 0x54, 0x72, 0xea, 0x96, 0x5f, 0xae, 0xdf, 0x15, 0x7b, 0x56, 0xa2, 0x99, 0x76,
	0xe8, 0x9d, 0x78, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xbd, 0x1e, 0x83, 0x79, 0x04, 0x00,
	0x00,
}

func (m *OlehOlehProduct) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OlehOlehProduct) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OlehOlehProduct) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Stock != 0 {
		i = encodeVarintOleholeh(dAtA, i, uint64(m.Stock))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ImageUrl) > 0 {
		i -= len(m.ImageUrl)
		copy(dAtA[i:], m.ImageUrl)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.ImageUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintOleholeh(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OlehOlehOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OlehOlehOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OlehOlehOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ShippingAddress) > 0 {
		i -= len(m.ShippingAddress)
		copy(dAtA[i:], m.ShippingAddress)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.ShippingAddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Total) > 0 {
		i -= len(m.Total)
		copy(dAtA[i:], m.Total)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Total)))
		i--
		dAtA[i] = 0x32
	}
	if m.Quantity != 0 {
		i = encodeVarintOleholeh(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Jamaah) > 0 {
		i -= len(m.Jamaah)
		copy(dAtA[i:], m.Jamaah)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.Jamaah)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProductName) > 0 {
		i -= len(m.ProductName)
		copy(dAtA[i:], m.ProductName)
		i = encodeVarintOleholeh(dAtA, i, uint64(len(m.ProductName)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProductId != 0 {
		i = encodeVarintOleholeh(dAtA, i, uint64(m.ProductId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintOleholeh(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		i--
		if m.ZeroFeeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOleholeh(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.OrderCount != 0 {
		i = encodeVarintOleholeh(dAtA, i, uint64(m.OrderCount))
		i--
		dAtA[i] = 0x20
	}
	if m.ProductCount != 0 {
		i = encodeVarintOleholeh(dAtA, i, uint64(m.ProductCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OrderList) > 0 {
		for iNdEx := len(m.OrderList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrderList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOleholeh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ProductList) > 0 {
		for iNdEx := len(m.ProductList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProductList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOleholeh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintOleholeh(dAtA []byte, offset int, v uint64) int {
	offset -= sovOleholeh(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OlehOlehProduct) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovOleholeh(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.ImageUrl)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	if m.Stock != 0 {
		n += 1 + sovOleholeh(uint64(m.Stock))
	}
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	return n
}

func (m *OlehOlehOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovOleholeh(uint64(m.Id))
	}
	if m.ProductId != 0 {
		n += 1 + sovOleholeh(uint64(m.ProductId))
	}
	l = len(m.ProductName)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Jamaah)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	if m.Quantity != 0 {
		n += 1 + sovOleholeh(uint64(m.Quantity))
	}
	l = len(m.Total)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.ShippingAddress)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 1 + l + sovOleholeh(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ZeroFeeEnabled {
		n += 2
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ProductList) > 0 {
		for _, e := range m.ProductList {
			l = e.Size()
			n += 1 + l + sovOleholeh(uint64(l))
		}
	}
	if len(m.OrderList) > 0 {
		for _, e := range m.OrderList {
			l = e.Size()
			n += 1 + l + sovOleholeh(uint64(l))
		}
	}
	if m.ProductCount != 0 {
		n += 1 + sovOleholeh(uint64(m.ProductCount))
	}
	if m.OrderCount != 0 {
		n += 1 + sovOleholeh(uint64(m.OrderCount))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovOleholeh(uint64(l))
	}
	return n
}

func sovOleholeh(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOleholeh(x uint64) (n int) {
	return sovOleholeh(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OlehOlehProduct) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOleholeh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OlehOlehProduct: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OlehOlehProduct: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stock", wireType)
			}
			m.Stock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOleholeh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOleholeh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OlehOlehOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOleholeh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OlehOlehOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OlehOlehOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductId", wireType)
			}
			m.ProductId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProductId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jamaah", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Jamaah = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShippingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShippingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOleholeh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOleholeh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOleholeh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZeroFeeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ZeroFeeEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipOleholeh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOleholeh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOleholeh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductList = append(m.ProductList, &OlehOlehProduct{})
			if err := m.ProductList[len(m.ProductList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderList = append(m.OrderList, &OlehOlehOrder{})
			if err := m.OrderList[len(m.OrderList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductCount", wireType)
			}
			m.ProductCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProductCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderCount", wireType)
			}
			m.OrderCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOleholeh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOleholeh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOleholeh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOleholeh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOleholeh(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOleholeh
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOleholeh
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOleholeh
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOleholeh
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOleholeh
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOleholeh        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOleholeh          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOleholeh = fmt.Errorf("proto: unexpected end of group")
)
